version: "3.7"

services:
  did-registry-api-v6-jsonrpc:
    image: did-registry-api-v6-jsonrpc
    build: .
    env_file:
      - .env.default
      - .env.default.local
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
