version: "3.7"

services:
  trusted-apps-registry-web-client:
    build:
      context: ../..
      args:
        REACT_APP_REGISTRY_ADDRESS: ${REACT_APP_REGISTRY_ADDRESS}
        REACT_APP_EBSI_CHAIN_ID: ${REACT_APP_EBSI_CHAIN_ID}
    image: 305472350643.dkr.ecr.eu-central-1.amazonaws.com/ebsi/trusted-apps-registry-web-client:prod-v0.0.24
