version: "3.7"

services:
  trusted-ledgers-sc-registry-api-v2:
    build: ../..
    image: 305472350643.dkr.ecr.eu-central-1.amazonaws.com/ebsi/trusted-ledgers-sc-registry-api-v2:pilot_ebsiint-4002-auth-updates_v2.0.0
