version: "3.7"

services:
  trusted-policies-registry-api:
    build: ../..
    image: 305472350643.dkr.ecr.eu-central-1.amazonaws.com/ebsi/trusted-policies-registry-api:pilot_ebsiint-3565-bootstrap_v1.0.0
