version: "3.7"

services:
  trusted-schemas-registry-api-v2:
    image: trusted-schemas-registry-api-v2
    build: .
    env_file:
      - .env.default
      - .env.default.local
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
