openapi: 3.1.0
info:
  title: Track and Trace API v1
  version: 1.0.0
  description: |
    Track and Trace (TnT) creates Proof of Origin with the following capabilities.

    - Proof of Origin
      - Aggregation of Events (partial proofs) of: by who, on behalf of, what, and when
    - Built in access management for did:key and did:ebsi
  contact:
    name: EBSI Support - Service Desk
    url: https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/11
  license:
    name: EUPL-1.2
    url: https://joinup.ec.europa.eu/page/eupl-text-11-12
paths:
  /track-and-trace/v1/documents:
    get:
      operationId: get-documents
      summary: List documents
      description: Returns a list of documents.
      tags:
        - Document
      parameters:
        - in: query
          name: page[after]
          schema:
            type: string
          description: Cursor that points to the end of the page of data that has been returned.
        - schema:
            type: integer
          in: query
          name: page[size]
          description: Defines the maximum number of objects that may be returned.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  self:
                    type: string
                    description: Absolute path to the collection (consult)
                  items:
                    type: array
                    description: List of documents
                    items:
                      type: object
                      properties:
                        documentId:
                          type: string
                          description: A unique record id = DID User
                        href:
                          type: string
                          description: Link to the resource
                  total:
                    type: integer
                    description: Total number of items across all pages.
                  pageSize:
                    type: integer
                    description: |
                      Maximum number of items per page. For the last page, its value should be
                      independent of the number of actually returned items.
                  links:
                    $ref: "#/components/schemas/Links"
              examples:
                "[test] Success":
                  value:
                    self: https://api-test.ebsi.eu/track-and-trace/v1/documents?page[after]=1&page[size]=10
                    items:
                      - documentId: "0xd06f39f1b07bdb5040665111ca96c63b100165f8e06ab2787d273d25ad6bb169"
                        href: https://api-test.ebsi.eu/track-and-trace/v1/documents/0xd06f39f1b07bdb5040665111ca96c63b100165f8e06ab2787d273d25ad6bb169
                      - documentId: "0x99ab5f3cfc581c53a9210fc4588416fbc84b3ff09950ddc84e0efd1e2b2e147a"
                        href: https://api-test.ebsi.eu/track-and-trace/v1/documents/0x99ab5f3cfc581c53a9210fc4588416fbc84b3ff09950ddc84e0efd1e2b2e147a
                      - documentId: "0x4ed9c02a2c28de4ebfb274f8036d961062b05d8ea7a06682725d36224718e03e"
                        href: https://api-test.ebsi.eu/track-and-trace/v1/documents/0x4ed9c02a2c28de4ebfb274f8036d961062b05d8ea7a06682725d36224718e03e
                      - documentId: "0xdd97695335b338c3de251247b533589cd2847000c4c0100a5ece17f28feb8640"
                        href: https://api-test.ebsi.eu/track-and-trace/v1/documents/0xdd97695335b338c3de251247b533589cd2847000c4c0100a5ece17f28feb8640
                      - documentId: "0xb64f68452c5b4a30ff952e4f873df8f5d340684d98b90417a6c26e9f48ff4e11"
                        href: https://api-test.ebsi.eu/track-and-trace/v1/documents/0xb64f68452c5b4a30ff952e4f873df8f5d340684d98b90417a6c26e9f48ff4e11
                      - documentId: "0x9a7897302b2967c8818ea2b61fa64138ea6f370640739f4a04957dd15c0c43e2"
                        href: https://api-test.ebsi.eu/track-and-trace/v1/documents/0x9a7897302b2967c8818ea2b61fa64138ea6f370640739f4a04957dd15c0c43e2
                      - documentId: "0x8edbce68309d79731a9e45bba4448b3c705e4074016e0f2cf994e8ad37e99b85"
                        href: https://api-test.ebsi.eu/track-and-trace/v1/documents/0x8edbce68309d79731a9e45bba4448b3c705e4074016e0f2cf994e8ad37e99b85
                      - documentId: "0x6e64123aaaa5d5e73fc878cc374e72bc9b7791f0048c968953d1943ea0138305"
                        href: https://api-test.ebsi.eu/track-and-trace/v1/documents/0x6e64123aaaa5d5e73fc878cc374e72bc9b7791f0048c968953d1943ea0138305
                      - documentId: "0x32a2334e9b8793fe4862ba6bac909e148b9ff98c4ca3ed54e598aa5cff63e670"
                        href: https://api-test.ebsi.eu/track-and-trace/v1/documents/0x32a2334e9b8793fe4862ba6bac909e148b9ff98c4ca3ed54e598aa5cff63e670
                      - documentId: "0xb08f451727fd50a5cd8433a86ce04302462477e7e978028d71094fc564dbad5e"
                        href: https://api-test.ebsi.eu/track-and-trace/v1/documents/0xb08f451727fd50a5cd8433a86ce04302462477e7e978028d71094fc564dbad5e
                    total: 98
                    pageSize: 10
                    links:
                      first: https://api-test.ebsi.eu/track-and-trace/v1/documents?page[after]=1&page[size]=10
                      prev: https://api-test.ebsi.eu/track-and-trace/v1/documents?page[after]=1&page[size]=10
                      next: https://api-test.ebsi.eu/track-and-trace/v1/documents?page[after]=2&page[size]=10
                      last: https://api-test.ebsi.eu/track-and-trace/v1/documents?page[after]=10&page[size]=10
        "400":
          description: Bad Request Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Bad Paging Request:
                  value:
                    title: Bad Paging Request
                    status: 400
                    detail: '["page[size] must not be greater than 50"]'
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
  /track-and-trace/v1/documents/{documentId}:
    get:
      tags:
        - Document
      summary: Get a document
      description: Gets the document corresponding to the ID.
      operationId: get-document
      parameters:
        - in: path
          name: documentId
          description: |
            The 32-bytes ID of the document, encoded in hexadecimal.
          required: true
          schema:
            type: string
          example: "0xd06f39f1b07bdb5040665111ca96c63b100165f8e06ab2787d273d25ad6bb169"
      responses:
        "200":
          description: Success.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Document"
              examples:
                Success:
                  value:
                    metadata: metadata
                    timestamp:
                      datetime: "0x65b24e0d"
                      source: block
                      proof: "0x0000000000000000000000000000000000000000000000000000000000000000"
                    events: []
                    creator: did:ebsi:ztqWJAmfyuUEf9Jvh97p167
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid {documentId} Parameter:
                  value:
                    title: Bad Request
                    status: 400
                    detail: '["documentId must be a valid document ID (32 bytes encoded in hexadecimal and starting with 0x)"]'
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Document Not Found:
                  $ref: "#/components/examples/NotFound"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
components:
  schemas:
    ProblemDetails:
      title: Problem Details
      description: A [Problem Details](https://datatracker.ietf.org/doc/html/rfc7807) object.
      type: object
      x-examples:
        Not Enough Credit:
          type: https://example.com/probs/out-of-credit
          title: You do not have enough credit.
          detail: Your current balance is 30, but that costs 50.
          instance: /account/12345/msgs/abc
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type. When dereferenced, it SHOULD provide
            human-readable documentation for the problem type.
          default: about:blank
        title:
          type: string
          description: |
            A short summary of the problem type.
          example: Internal Server Error
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 400
          maximum: 600
          example: 500
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the problem.
          example: Connection timeout
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem. It may or may
            not yield further information if dereferenced.
    Links:
      title: Links
      description: Links model used for pagination
      type: object
      properties:
        last:
          type: string
          description: URI of the last page
        prev:
          type: string
          description: URI of the previous page
        next:
          type: string
          description: URI of the next page
        first:
          type: string
          description: URI of the first page
    Document:
      title: Document
      description: Track and Trace Document
      type: object
      properties:
        documentMetadata:
          description: Document's metadata
          type: string
        documentTimestamp:
          description: Timestamp object
          type: object
          properties:
            datetime:
              type: string
              description: |
                The date and time, optionally from transaction input
            source:
              type: string
              description: |
                Defines how the datetime was resolved, enumerated options are "block" and "external"
            proof:
              type: string
              description: |
                Proof of the source. Either a block number or a hash of timestamp certificate
        events:
          type: array
          description: List of event hashes
          items:
            type: string
            description: Event hash
        creator:
          type: string
          description: The `did:key` or `did:ebsi` that created the document
  examples:
    BadRequest:
      value:
        title: Bad request
        status: 400
        detail: Bad request
    InvalidToken:
      value:
        title: Invalid token
        status: 400
        detail: Invalid token
    NotFound:
      value:
        title: Not found
        status: 404
        detail: Not found
    InternalError:
      value:
        title: Internal error
        status: 500
        detail: Internal error
servers:
  - url: http://localhost
    description: Local Computer Environment
  - url: https://api-test.ebsi.eu
    description: EBSI Test Environment
  - url: https://api-pilot.ebsi.eu
    description: EBSI Pilot Environment
  - url: https://api-conformance.ebsi.eu
    description: EBSI Conformance Environment
