openapi: 3.1.0
info:
  title: Track and Trace API v1
  version: 1.0.0
  description: |
    Track and Trace (TnT) creates Proof of Origin with the following capabilities.

    - Proof of Origin
      - Aggregation of Events (partial proofs) of: by who, on behalf of, what, and when
    - Built in access management for did:key and did:ebsi
  contact:
    name: EBSI Support - Service Desk
    url: https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/11
  license:
    name: EUPL-1.2
    url: https://joinup.ec.europa.eu/page/eupl-text-11-12
paths:
  /track-and-trace/v1/documents:
    get:
      operationId: get-documents
      summary: List documents
      description: Returns a list of documents.
      tags:
        - Document
      parameters:
        - in: query
          name: page[after]
          schema:
            type: string
          description: Cursor that points to the end of the page of data that has been returned.
        - schema:
            type: integer
          in: query
          name: page[size]
          description: Defines the maximum number of objects that may be returned.
        - in: query
          name: public_key_id
          schema:
            type: string
          description: Filter results by public key id
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Bad Request Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Bad Paging Request:
                  value:
                    title: Bad Paging Request
                    status: 400
                    detail: PageSize should not be greater than 50
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
components:
  schemas:
    ProblemDetails:
      title: Problem Details
      description: A [Problem Details](https://datatracker.ietf.org/doc/html/rfc7807) object.
      type: object
      x-examples:
        Not Enough Credit:
          type: https://example.com/probs/out-of-credit
          title: You do not have enough credit.
          detail: Your current balance is 30, but that costs 50.
          instance: /account/12345/msgs/abc
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type. When dereferenced, it SHOULD provide
            human-readable documentation for the problem type.
          default: about:blank
        title:
          type: string
          description: |
            A short summary of the problem type.
          example: Internal Server Error
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 400
          maximum: 600
          example: 500
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the problem.
          example: Connection timeout
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem. It may or may
            not yield further information if dereferenced.
  examples:
    BadRequest:
      value:
        title: Bad request
        status: 400
        detail: Bad request
    InvalidToken:
      value:
        title: Invalid token
        status: 400
        detail: Invalid token
    NotFound:
      value:
        title: Not found
        status: 404
        detail: Not found
    InternalError:
      value:
        title: Internal error
        status: 500
        detail: Internal error
servers:
  - url: http://localhost
    description: Local Computer Environment
  - url: https://api-test.ebsi.eu
    description: EBSI Test Environment
  - url: https://api-pilot.ebsi.eu
    description: EBSI Pilot Environment
  - url: https://api-conformance.ebsi.eu
    description: EBSI Conformance Environment
