version: "3.7"

services:
  trusted-issuers-registry-api-v4:
    image: trusted-issuers-registry-api-v4
    build: .
    env_file:
      - .env.default
      - .env.default.local
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
