# .graphclientrc.yml
sources:
  - name: TrustedPoliciesRegistry
    handler:
      graphql:
        endpoint: "{context.myCustomEndpoint}"
        source: "./schema.graphql"
documents:
  - ./src/modules/policies/queries/queries.graphql
  - ./src/modules/users/queries/queries.graphql
