schema {
  query: Query
}

type Policy {
  id: String!
  policyName: String!
  description: String!
  status: Boolean!
}

type User {
  id: String!
  attributes: [String!]!
}

input Policy_filter {
  policyName: String
  status: Boolean
}

input User_filter {
  attributes_contains: [String!]
}

type _Block_ {
  timestamp: Int!
}

type _Meta_ {
  block: _Block_!
}

type Query {
  policies(skip: Int = 0, first: Int = 100, where: Policy_filter): [Policy!]!
  users(skip: Int = 0, first: Int = 100, where: User_filter): [User!]!
  user(id: ID!): User
  _meta: _Meta_!
}
