ignored:
  - DL3018
  - DL3015 # allow installing recommended packages
  - DL3059 # allow loose version package on apk installation
  - DL3006 # allow starting from core-services without specific tag
