version: "3.7"

services:
  besu:
    build: .
    container_name: storage-api
    ports:
      - "8080:8080"
    environment:
      - EBSI_ENV=integration
      - API_STORAGE_PRIVATE_KEY=${API_STORAGE_PRIVATE_KEY}
