version: "3.4"

services:
  notarization:
    image: notarization:latest
    restart: always
    logging:
      options:
        max-size: "100m"
        max-file: "50"
    ports:
      - "3000:3000"
    container_name: notarization

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
