sonar.projectKey=ledger-api
sonar.projectName=ledger-api
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=api
sonar.exclusions=**/node_modules/**,**/*.test.js
sonar.tests=packages/besu/src/tests
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=packages/besu/src/coverage/lcov.info
sonar.testExecutionReportPaths=packages/besu/src/sonar-report.xml