sonar.projectKey=4-ebsi-api
sonar.projectName=4-ebsi-api
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=apis
sonar.exclusions=**/node_modules/**,**/*.test.js
sonar.tests=tests
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=sonar-report.xml