version: "3.7"

services:
  trusted-ledgers-sc-registry-api:
    build: ../..
    image: 305472350643.dkr.ecr.eu-central-1.amazonaws.com/ebsi/trusted-ledgers-sc-registry-api:conformance_ebsiint-3848-tpr-updates_v1.0.0
