version: "3.7"

services:
  trusted-apps-registry-v3:
    build: ../..
    image: 305472350643.dkr.ecr.eu-central-1.amazonaws.com/ebsi/trusted-apps-registry-v3:conformance_ebsiint-3845-tpr-updates_v3.0.0
