query GetIssuers($skip: Int!, $pagesize: Int!) {
  issuers(first: $pagesize, skip: $skip) {
    id
  }
}

query GetIssuer($did: String!) {
  issuer(id: $did) {
    attributes(first: 1000, skip: 0) {
      lastRevision {
        id
        data
        issuerType
        tao
        rootTao
      }
    }
  }
}

query GetAttributes($did: String!, $skip: Int!, $pagesize: Int!) {
  issuer(id: $did) {
    attributes(first: $pagesize, skip: $skip) {
      id
    }
  }
}

query GetAttribute($did: String!, $attributeId: String!) {
  issuer(id: $did) {
    attributes(first: 1, skip: 0, where: { id: $attributeId }) {
      lastRevision {
        id
        data
        issuerType
        tao
        rootTao
      }
    }
  }
}

query GetRevisions(
  $did: String!
  $attributeId: String!
  $skip: Int!
  $pagesize: Int!
) {
  issuer(id: $did) {
    attributes(first: 1, skip: 0, where: { id: $attributeId }) {
      revisions(first: $pagesize, skip: $skip) {
        id
        data
        issuerType
        tao
        rootTao
      }
    }
  }
}

query GetProxies($did: String!, $skip: Int!, $pagesize: Int!) {
  issuer(id: $did) {
    proxies(first: $pagesize, skip: $skip) {
      id
    }
  }
}

query GetProxy($did: String!, $proxyId: String!) {
  issuer(id: $did) {
    proxies(first: 1, skip: 0, where: { id: $proxyId }) {
      data
    }
  }
}
