query GetSchemas($skip: Int!, $pagesize: Int!, $where: Schema_filter) {
  schemas(first: $pagesize, skip: $skip, where: $where) {
    id
  }
}

query GetSchema($schemaId: String!) {
  schema(id: $schemaId) {
    lastRevision {
      content
    }
  }
}

query GetRevisions(
  $schemaId: String!
  $skip: Int!
  $pagesize: Int!
  $where: Revision_filter
) {
  schema(id: $schemaId) {
    revisions(first: $pagesize, skip: $skip, where: $where) {
      id
    }
  }
}

query GetAllRevisionsWithMetadata($schemaId: String!, $where: Revision_filter) {
  schema(id: $schemaId) {
    revisions(first: 1000, skip: 0, where: $where) {
      id
      metadata(first: 1000, skip: 0) {
        content
      }
    }
  }
}

query GetRevision($schemaId: String!, $revisionId: String!) {
  schema(id: $schemaId) {
    revisions(first: 1, skip: 0, where: { id: $revisionId }) {
      content
    }
  }
}

query GetMetadatas(
  $schemaId: String!
  $revisionId: String!
  $skip: Int!
  $pagesize: Int!
  $where: Metadata_filter
) {
  schema(id: $schemaId) {
    revisions(first: 1, skip: 0, where: { id: $revisionId }) {
      metadata(first: $pagesize, skip: $skip, where: $where) {
        id
      }
    }
  }
}

query GetMetadata(
  $schemaId: String!
  $revisionId: String!
  $metadataId: String!
) {
  schema(id: $schemaId) {
    revisions(first: 1, skip: 0, where: { id: $revisionId }) {
      metadata(first: 1, skip: 0, where: { id: $metadataId }) {
        content
      }
    }
  }
}
