version: "3.7"

services:
  trusted-schemas-registry-api-v2:
    build: ../..
    image: 305472350643.dkr.ecr.eu-central-1.amazonaws.com/ebsi/trusted-schemas-registry-api-v2:prod_ebsiint-4750-update-libs_v2.0.0
