interface JsonRpcErrorObject {
  jsonrpc: string;
  error: {
    code: number;
    message: string;
    data?: unknown;
  };
  id: string | number | null;
}

export class JsonRpcError extends Error {
  public jsonrpc: string;

  public error: {
    code: number;
    message: string;
    data?: unknown;
  };

  public id: number | string | null;

  public status: number;

  /**
   * @param code A Number that indicates the error type that occurred. This MUST be an integer.
   * @param status The HTTP status code generated by the origin server for this occurrence of the problem.
   * @param message A String providing a short description of the error. The message SHOULD be limited to a concise single sentence.
   * @param id It MUST be the same as the value of the id member in the Request Object. If there was an error in detecting the id in the Request object (e.g. Parse error/Invalid Request), it MUST be Null.
   * @param data A Primitive or Structured value that contains additional information about the error. This may be omitted.
   */
  constructor(
    code: number,
    status: number,
    message: string,
    id: string | number | null,
    data?: unknown
  ) {
    super(message);
    this.name = "JsonRpcError";
    this.jsonrpc = "2.0";
    this.status = status;
    this.error = { code, message, data };
    this.id = id;
  }

  toJSON(): JsonRpcErrorObject {
    return {
      jsonrpc: this.jsonrpc,
      error: this.error,
      id: this.id,
    };
  }

  toString(): string {
    return `${this.error.code} - ${this.error.message}`;
  }
}

export default JsonRpcError;
