schema {
  query: Query
}

enum Source {
  block
  external
}

enum Permission {
  delegate
  write
  creator
}

enum Event_orderBy {
  id
  externalHash
  hash
  timestamp
  source
  proof
  sender
  origin
  metadata
}

input Document_filter {
  creator: String
  source: Source
}

input Event_filter {
  id: String
  externalHash: String
  source: Source
  sender: String
  origin: String
}

input Invitation_filter {
  type: Permission
  grantedBy: String
  subject: String
}

type Creator {
  id: String!
  active: Boolean!
  documents(
    first: Int = 100
    skip: Int = 0
    where: Document_filter
  ): [Document!]!
}

type Operator {
  id: String!
  invitations(
    first: Int = 100
    skip: Int = 0
    where: Invitation_filter
  ): [Invitation!]!
}

type Document {
  id: String!
  creator: String!
  timestamp: String!
  source: Source!
  proof: String!
  metadata: String!
  events(
    first: Int = 100
    skip: Int = 0
    orderby: Event_orderBy
    where: Event_filter
  ): [Event!]!
  invitations(
    first: Int = 100
    skip: Int = 0
    where: Invitation_filter
  ): [Invitation!]!
}

type Invitation {
  id: String!
  document: Document!
  type: Permission!
  grantedBy: String!
  subject: String!
  children(first: Int = 100, skip: Int = 0): [Invitation!]!
}

type Event {
  id: String!
  externalHash: String!
  hash: String!
  timestamp: String!
  source: Source!
  proof: String!
  sender: String!
  origin: String!
  metadata: String!
}

type _Block_ {
  timestamp: Int!
}

type _Meta_ {
  block: _Block_!
}

type Query {
  creators(first: Int = 100, skip: Int = 0): [Creator!]!
  operators(first: Int = 100, skip: Int = 0): [Operator!]!
  documents(
    first: Int = 100
    skip: Int = 0
    where: Document_filter
  ): [Document!]!
  invitations(
    first: Int = 100
    skip: Int = 0
    where: Invitation_filter
  ): [Invitation!]!
  events(
    first: Int = 100
    skip: Int = 0
    orderby: Event_orderBy
    where: Event_filter
  ): [Event!]!
  creator(id: String!): Creator!
  operator(id: String!): Operator!
  document(id: String!): Document!
  invitation(id: String!): Invitation!
  event(id: String!): Event!
  _meta: _Meta_!
}
