# This is an example docker-compose.yml that shows you how to run the project locally
# It is not meant to be used as is in production
version: "3.7"

services:
  users-onboarding-web-client-v2:
    env_file:
      - .env
      - .env.local
    build:
      context: .
      args:
        PUBLIC_URL: ${PUBLIC_URL}
    ports:
      - "8080:8080"
