version: "3.7"

services:
  ledger-api-v3:
    image: ledger-api-v3
    build: .
    env_file:
      - .env.default
      - .env.default.local
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
