query GetDocuments($skip: Int!, $pagesize: Int!, $where: Document_filter) {
  documents(first: $pagesize, skip: $skip, where: $where) {
    id
  }
}

query GetDocument($documentId: String!) {
  document(id: $documentId) {
    creator
    timestamp
    source
    proof
    metadata
    events(first: 1000, skip: 0, orderBy: timestamp) {
      id
    }
  }
}

query GetDocumentEvents(
  $documentId: String!
  $skip: Int!
  $pagesize: Int!
  $where: Event_filter
) {
  document(id: $documentId) {
    events(first: $pagesize, skip: $skip, orderBy: timestamp, where: $where) {
      id
    }
  }
}

query GetDocumentEvent($documentId: String!, $eventId: String!) {
  document(id: $documentId) {
    events(first: 1, skip: 0, orderBy: timestamp, where: { id: $eventId }) {
      sender
      hash
      externalHash
      timestamp
      source
      proof
      metadata
      origin
    }
  }
}

query GetDocumentInvitations(
  $documentId: String!
  $skip: Int!
  $pagesize: Int!
  $where: Invitation_filter
) {
  document(id: $documentId) {
    invitations(first: $pagesize, skip: $skip, where: $where) {
      subject
      grantedBy
      type
    }
  }
}

query GetCreator($did: String!) {
  creator(id: $did) {
    active
  }
}

query GetOperator(
  $subject: String!
  $skip: Int!
  $pagesize: Int!
  $where: Invitation_filter
) {
  operator(id: $subject) {
    invitations(first: $pagesize, skip: $skip, where: $where) {
      subject
      grantedBy
      type
      document {
        id
      }
    }
  }
}

query GetBlockTimestamp {
  _meta {
    block {
      timestamp
    }
  }
}
