version: "3.7"

services:
  did-registry-api-v5:
    image: did-registry-api-v5
    build: .
    env_file:
      - .env.default
      - .env.default.local
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
