enum Source {
  block
  external
}

enum Permission {
  delegate
  write
  creator
}

type Creator @entity(immutable: false) {
  id: String!
  active: Boolean!
  documents: [Document!]! @derivedFrom(field: "creator")
}

type Operator @entity(immutable: true) {
  id: Bytes!
  invitations: [Invitation!]! @derivedFrom(field: "subject")
}

type Document @entity(immutable: false) {
  id: Bytes!
  creator: Creator!
  timestamp: BigInt!
  source: Source!
  proof: Bytes!
  metadata: String!
  events: [Event!]! @derivedFrom(field: "document")
  invitations: [Invitation!]! @derivedFrom(field: "document")
}

type Invitation @entity(immutable: false) {
  id: Bytes! # Set to document.id.concat(subject.id).concatI32(permission)
  document: Document!
  type: Permission!
  grantedBy: Bytes!
  subject: Operator!
  parent: Invitation
  children: [Invitation!]! @derivedFrom(field: "parent")
}

# `Event` is not immutable because it can be removed
type Event @entity(immutable: false) {
  id: Bytes! # Set to document.id.concat(event.eventHash)
  document: Document!
  externalHash: String!
  hash: Bytes!
  timestamp: BigInt!
  source: Source!
  proof: Bytes!
  sender: Bytes!
  origin: String!
  metadata: String!
}
