version: "3.7"

services:
  fabric:
    build: .
    container_name: fabric-api
    ports:
      - ${PORT_FABRIC}:8080
    environment:
      - FABRIC_USERNAME=${FABRIC_USERNAME}
      - FABRIC_PASSWORD=${FABRIC_PASSWORD}
      - ORG_NAME=${ORG_NAME}
      - CA_URL=${CA_URL}
      - CA_MSP_ID=${CA_MSP_ID}
      - PEER_NODE_NAME=${PEER_NODE_NAME}
      - PEER_NODE_URL=${PEER_NODE_URL}
      - ORDERER_NODE_NAME=${ORDERER_NODE_NAME}
      - ORDERER_NODE_URL=${ORDERER_NODE_URL}
    volumes:
      - ./ssl:/api/ssl/
      - ./src/main/resources/server.jks:/api/server.jks
      - ./wallet:/api/wallet/
