enum Source {
  block
  external
}

enum Permission {
  delegate
  write
  creator
}

type Creator @entity(immutable: false) {
  id: String!
  active: Boolean!
  documents: [Document!]!
}

type Operator @entity(immutable: false) {
  id: Bytes!
  invitations: [Invitation!]!
}

type Document @entity(immutable: false) {
  id: Bytes!
  creator: String!
  timestamp: BigInt!
  source: Source!
  proof: Bytes!
  metadata: String!
  events: [Event!]!
  invitations: [Invitation!]!
}

type Invitation @entity(immutable: false) {
  id: String!
  document: Document!
  type: Permission!
  grantedBy: Bytes!
  subject: Bytes!
  children: [Invitation!]!
}

type Event @entity(immutable: false) {
  id: Bytes!
  externalHash: String!
  hash: Bytes!
  timestamp: BigInt!
  source: Source!
  proof: Bytes!
  sender: Bytes!
  origin: String!
  metadata: String!
}
