openapi: 3.0.3
info:
  title: Timestamp API
  description: |
    Timestamp API is a Core Service of the EBSI platform providing the capability of checking the authenticity of a digital document by verifying the presence and the timestamp of the document's hash in a specific smart contract.
  version: 1.0.0
  termsOfService: "/docs/terms"
  contact:
    name: "EBSI Support"
    url: "https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/ebsi"
  license:
    name: "EUPL-1.2"
    url: "https://joinup.ec.europa.eu/page/eupl-text-11-12"
paths:
  /timestamp/v1/hashes:
    get:
      tags:
        - Timestamp
      summary: Get a list of records
      description: Returns a list of records.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    description: list of channel names
                    type: array
                    items:
                      $ref: "#/components/schemas/hash"
                  total:
                    type: integer
                    description: "total number of pages in a collection"
                  pageSize:
                    type: integer
                    description: number of items to be return per page
                  links:
                    $ref: "#/components/schemas/links"
              examples:
                Get Records:
                  value:
                    items:
                      - hash: 23...d7f
                        txHash: 0x12...ba
                        timestamp: "2019-10-23T14:25:20+00:00"
                        registeredBy: 0xfa...94
                        blockNumber: 739688
                      - hash: 13...d7f
                        txHash: 0x32...ba
                        timestamp: "2019-10-23T14:26:20+00:00"
                        registeredBy: 0xfa...94
                        blockNumber: 739689
                    total: 13
                    pageSize: 2
                    links:
                      first: "/timestamp/v1/hashes?page[after]=0&page[size]=2"
                      prev: "/timestamp/v1/hashes?page[after]=2&page[size]=2"
                      next: "/timestamp/v1/hashes?page[after]=4&page[size]=2"
                      last: "/timestamp/v1/hashes?page[after]=13&page[size]=2"
        "500":
          description: Internal Server Error
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
      operationId: get-timestamp-v1-hashes
      parameters:
        - in: query
          name: "page[before]"
          schema:
            type: string
          description: Cursor that points to the start of the page of data that has been returned.
        - in: query
          name: "page[after]"
          schema:
            type: string
          description: Cursor that points to the end of the page of data that has been returned.
        - schema:
            type: integer
          in: query
          name: "page[size]"
          description: Defines the maximum number of objects that may be returned.
  "/timestamp/v1/hashes/{hash}":
    get:
      tags:
        - Timestamp
      summary: Get a record by its hash
      description: Retrieve notarization record from the smart contract by the hash of the notarized document. If the hash exists in the smart contract, it will return the timestamp (epoch time) and the address that performed the notarization.
      parameters:
        - name: hash
          in: path
          schema:
            type: string
          example: "0xbe5b5152fcd01b6bf53f149bfd1493a49ec5e8ae94cc4c29a81563eea0e347f4"
          required: true
      responses:
        "200":
          description: Record exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/hash"
              examples:
                Get a Record:
                  value:
                    hash: 23...7f
                    txHash: 0x12...ba
                    timestamp: "2019-10-23T14:25:20+00:00"
                    registeredBy: 0xfa...94
                    blockNumber: 739688
        "400":
          description: Bad Request
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Bad Request:
                  $ref: "#/components/examples/BadRequest"
                Hash Not Valid:
                  value:
                    title: Bad Request
                    status: 400
                    detail: "The format of {hash} parameter is not valid"
        "404":
          description: Store Does Not Exist
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Not Found:
                  value:
                    title: Not Found
                    status: 404
                    detail: "{hash} parameter not found"
        "500":
          description: Internal Server Error
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
      operationId: get-timestamp-v1-hash
components:
  schemas:
    Problem:
      description: A Problem Details object (RFC 7807)
      type: object
      x-examples:
        Not Enough Credit:
          type: "https://example.com/probs/out-of-credit"
          title: You do not have enough credit.
          detail: "Your current balance is 30, but that costs 50."
          instance: /account/12345/msgs/abc
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type.
          default: "about:blank"
        title:
          type: string
          description: |
            A short summary of the problem type.
          example: Internal Server Error
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 400
          maximum: 600
          exclusiveMaximum: true
          example: 500
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the problem.
          example: Connection timeout
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
    hash:
      type: object
      description: Notarized Document Record
      x-examples:
        Hash example:
          hash: 23...d7f
          txHash: 0x12...ba
          timestamp: "2019-10-23T14:25:20+00:00"
          registeredBy: 0xfa...94
          blockNumber: 739688
      title: Record
      properties:
        hash:
          type: string
          example: 892c9637814ccd39256cbaa03250c92507ae183dda03d091fc24a3221ecae303
          description: keccak-256 hash of the file
        txHash:
          type: string
          example: "0x561de67a9789b20bedf627e97bf6444206f83ad6e5c29c692d8cc52c352c0676"
          description: Valid Ethereum transaction hash
        blockNumber:
          type: integer
          example: 900
          description: Number of the block containing the transaction
        registeredBy:
          type: string
          example: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
          description: Valid Ethereum Address
        timestamp:
          type: string
          example: "2019-10-23T14:25:20+00:00"
          description: Timestamp converted to ISO 8601 format
    links:
      title: Links
      type: object
      properties:
        last:
          type: string
          description: " URI of the last page"
        prev:
          type: string
          description: " URI of the previous page"
        next:
          type: string
          description: " URI of the next page"
        first:
          type: string
          description: " URI of the first page"
      description: Links model used for pagination
      x-examples:
        Links:
          first: "/timestamp/v1/hashes?page[after]=0&page[size]=2"
          prev: "/timestamp/v1/hashes?page[after]=2&page[size]=2"
          next: "/timestamp/v1/hashes?page[after]=4&page[size]=2"
          last: "/timestamp/v1/hashes?page[after]=13&page[size]=2"
  examples:
    BadRequest:
      value:
        title: Bad Request
        status: 400
        detail: Bad request
    InvalidToken:
      value:
        title: Invalid Token
        status: 400
        detail: Invalid token
    Unauthorized:
      value:
        title: Unauthorized
        status: 401
        detail: Unauthorized
    Forbidden:
      value:
        title: Forbidden
        status: 403
        detail: Forbidden
    NotFound:
      value:
        title: Not Found
        status: 404
        detail: Not found
    TooLarge:
      value:
        title: Payload Too Large
        status: 413
        detail: Payload too large
    InternalError:
      value:
        title: Internal Server Error
        status: 500
        detail: Internal error
    ListFiles:
      value:
        items:
          - hash1
          - hash2
        total: 2
    ListFilesPagination:
      value:
        items:
          - hash1
          - hash2
        total: 2
        pageSize: 3
        links:
          first: "/timestamp/v1/hashes?page[after]=fff&page[size]=2"
          prev: "/timestamp/v1/hashes?page[after]=ppp&page[size]=2"
          next: "/timestamp/v1/hashes?page[after]=nnn&page[size]=2"
          last: "/timestamp/v1/hashes?page[after]=lll&page[size]=2"
tags:
  - name: Timestamp
    description: Validate timestamped records
servers:
  - url: "http://localhost"
    description: Local Computer Environment
  - url: "https://api.ebsi.xyz"
    description: EBSI Testing Environment
