schema {
  query: Query
}

enum IssuerType {
  Undefined
  RootTAO
  TAO
  TI
  Revoked
}

input BlockChangedFilter {
  number_gte: Int!
}

input Revision_filter {
  id: String
  id_not: String
  id_gt: String
  id_lt: String
  id_gte: String
  id_lte: String
  id_in: [String!]
  id_not_in: [String!]
  id_contains: String
  id_not_contains: String
  data: String
  data_not: String
  data_gt: String
  data_lt: String
  data_gte: String
  data_lte: String
  data_in: [String!]
  data_not_in: [String!]
  data_contains: String
  data_contains_nocase: String
  data_not_contains: String
  data_not_contains_nocase: String
  data_starts_with: String
  data_starts_with_nocase: String
  data_not_starts_with: String
  data_not_starts_with_nocase: String
  data_ends_with: String
  data_ends_with_nocase: String
  data_not_ends_with: String
  data_not_ends_with_nocase: String
  issuerType: IssuerType
  issuerType_not: IssuerType
  issuerType_in: [IssuerType!]
  issuerType_not_in: [IssuerType!]
  tao: String
  tao_not: String
  tao_gt: String
  tao_lt: String
  tao_gte: String
  tao_lte: String
  tao_in: [String!]
  tao_not_in: [String!]
  tao_contains: String
  tao_contains_nocase: String
  tao_not_contains: String
  tao_not_contains_nocase: String
  tao_starts_with: String
  tao_starts_with_nocase: String
  tao_not_starts_with: String
  tao_not_starts_with_nocase: String
  tao_ends_with: String
  tao_ends_with_nocase: String
  tao_not_ends_with: String
  tao_not_ends_with_nocase: String
  rootTao: String
  rootTao_not: String
  rootTao_gt: String
  rootTao_lt: String
  rootTao_gte: String
  rootTao_lte: String
  rootTao_in: [String!]
  rootTao_not_in: [String!]
  rootTao_contains: String
  rootTao_contains_nocase: String
  rootTao_not_contains: String
  rootTao_not_contains_nocase: String
  rootTao_starts_with: String
  rootTao_starts_with_nocase: String
  rootTao_not_starts_with: String
  rootTao_not_starts_with_nocase: String
  rootTao_ends_with: String
  rootTao_ends_with_nocase: String
  rootTao_not_ends_with: String
  rootTao_not_ends_with_nocase: String
  _change_block: BlockChangedFilter
  and: [Revision_filter]
  or: [Revision_filter]
}

input Attribute_filter {
  id: String
  id_not: String
  id_gt: String
  id_lt: String
  id_gte: String
  id_lte: String
  id_in: [String!]
  id_not_in: [String!]
  id_contains: String
  id_not_contains: String
  revisions: [String!]
  revisions_not: [String!]
  revisions_contains: [String!]
  revisions_contains_nocase: [String!]
  revisions_not_contains: [String!]
  revisions_not_contains_nocase: [String!]
  revisions_: Revision_filter
  lastRevision: String
  lastRevision_not: String
  lastRevision_gt: String
  lastRevision_lt: String
  lastRevision_gte: String
  lastRevision_lte: String
  lastRevision_in: [String!]
  lastRevision_not_in: [String!]
  lastRevision_contains: String
  lastRevision_contains_nocase: String
  lastRevision_not_contains: String
  lastRevision_not_contains_nocase: String
  lastRevision_starts_with: String
  lastRevision_starts_with_nocase: String
  lastRevision_not_starts_with: String
  lastRevision_not_starts_with_nocase: String
  lastRevision_ends_with: String
  lastRevision_ends_with_nocase: String
  lastRevision_not_ends_with: String
  lastRevision_not_ends_with_nocase: String
  lastRevision_: Revision_filter
  _change_block: BlockChangedFilter
  and: [Attribute_filter]
  or: [Attribute_filter]
}

input Proxy_filter {
  id: String
  id_not: String
  id_gt: String
  id_lt: String
  id_gte: String
  id_lte: String
  id_in: [String!]
  id_not_in: [String!]
  id_contains: String
  id_not_contains: String
  data: String
  data_not: String
  data_gt: String
  data_lt: String
  data_gte: String
  data_lte: String
  data_in: [String!]
  data_not_in: [String!]
  data_contains: String
  data_contains_nocase: String
  data_not_contains: String
  data_not_contains_nocase: String
  data_starts_with: String
  data_starts_with_nocase: String
  data_not_starts_with: String
  data_not_starts_with_nocase: String
  data_ends_with: String
  data_ends_with_nocase: String
  data_not_ends_with: String
  data_not_ends_with_nocase: String
  _change_block: BlockChangedFilter
  and: [Proxy_filter]
  or: [Proxy_filter]
}

input Issuer_filter {
  id: String
  id_not: String
  id_gt: String
  id_lt: String
  id_gte: String
  id_lte: String
  id_in: [String!]
  id_not_in: [String!]
  id_contains: String
  id_contains_nocase: String
  id_not_contains: String
  id_not_contains_nocase: String
  id_starts_with: String
  id_starts_with_nocase: String
  id_not_starts_with: String
  id_not_starts_with_nocase: String
  id_ends_with: String
  id_ends_with_nocase: String
  id_not_ends_with: String
  id_not_ends_with_nocase: String
  attributes: [String!]
  attributes_not: [String!]
  attributes_contains: [String!]
  attributes_contains_nocase: [String!]
  attributes_not_contains: [String!]
  attributes_not_contains_nocase: [String!]
  attributes_: Attribute_filter
  proxies: [String!]
  proxies_not: [String!]
  proxies_contains: [String!]
  proxies_contains_nocase: [String!]
  proxies_not_contains: [String!]
  proxies_not_contains_nocase: [String!]
  proxies_: Proxy_filter
  _change_block: BlockChangedFilter
  and: [Issuer_filter]
  or: [Issuer_filter]
}

type Issuer {
  id: String!
  attributes(
    first: Int = 100
    skip: Int = 0
    where: Attribute_filter
  ): [Attribute!]!
  proxies(first: Int = 100, skip: Int = 0, where: Proxy_filter): [Proxy!]!
}

type Attribute {
  id: String!
  revisions(
    first: Int = 100
    skip: Int = 0
    where: Revision_filter
  ): [Revision!]!
  lastRevision: Revision!
}

type Revision {
  id: String!
  data: String!
  issuerType: String!
  tao: String!
  rootTao: String!
}

type Proxy {
  id: String!
  data: String!
}

type _Block_ {
  timestamp: Int!
}

type _Meta_ {
  block: _Block_!
}

type Query {
  issuers(skip: Int = 0, first: Int = 100, where: Issuer_filter): [Issuer!]!
  issuer(id: String!): Issuer!
  attributes(
    skip: Int = 0
    first: Int = 100
    where: Attribute_filter
  ): [Attribute!]!
  attribute(id: String!): Attribute
  revisions(
    skip: Int = 0
    first: Int = 100
    where: Revision_filter
  ): [Revision!]!
  revision(id: String!): Revision!
  proxies(skip: Int = 0, first: Int = 100, where: Proxy_filter): [Proxy!]!
  proxy(id: String!): Proxy!
  _meta: _Meta_!
}
