query GetDids($skip: Int!, $pagesize: Int!) {
  didDocuments(first: $pagesize, skip: $skip) {
    ...DocumentsFields
  }
}

query GetDidsByController($controller: String!, $skip: Int!, $pagesize: Int!) {
  didDocuments(
    first: $pagesize
    skip: $skip
    where: { controllers_: { controller: $controller } }
  ) {
    ...DocumentsFields
  }
}

query GetDidsByVerificationRelationship(
  $vMethodId: String!
  $vRelationship: String!
  $skip: Int!
  $pagesize: Int!
) {
  didDocuments(
    first: $pagesize
    skip: $skip
    where: {
      verificationRelationships_: {
        and: [{ name: $vRelationship }, { vMethodId: $vMethodId }]
      }
    }
  ) {
    ...DocumentsFields
  }
}

query GetDidsByControllerAndVerificationRelationshipQuery(
  $controller: String
  $vMethodId: String
  $vRelationship: String
  $skip: Int
  $pagesize: Int
) {
  didDocuments(
    first: $pagesize
    skip: $skip
    where: {
      and: [
        { controllers_: { controller: $controller } }
        {
          verificationRelationships_: {
            and: [{ name: $vRelationship }, { vMethodId: $vMethodId }]
          }
        }
      ]
    }
  ) {
    ...DocumentsFields
  }
}

query GetDidDocumentByTimestamp($id: ID!, $did: String, $timestamp: BigInt!) {
  didDocument(id: $id) {
    ...DocumentFieldsByTimestamp
  }
}

query GetDidDocumentEvents($did: ID!, $skip: Int, $pagesize: Int) {
  didDocument(id: $did) {
    ...DidDocumentEvents
  }
}

query GetControllers($did: ID!, $timestamp: BigInt!) {
  didDocument(id: $did) {
    controllers(first: 100) {
      controller {
        verificationMethods(where: { isSecp256k1: true }) {
          publicKey
          id
        }
        verificationRelationships(
          where: {
            and: [
              { name: "capabilityInvocation" }
              { notBefore_lte: $timestamp }
              { notAfter_gte: $timestamp }
            ]
          }
        ) {
          vMethodId
        }
      }
    }
  }
}

fragment DocumentsFields on DidDocument {
  baseDocument
  id
}

fragment DocumentFields on DidDocument {
  id
  baseDocument
  controllers {
    id
    controller {
      id
    }
    controlledDocument {
      id
    }
    status
  }
  verificationRelationships {
    id
    name
    vMethodId
    notBefore
    notAfter
  }
  verificationMethods {
    id
    publicKey
    isSecp256k1
    status
  }
}

fragment DocumentFieldsByTimestamp on DidDocument {
  baseDocument
  id
  controllers {
    id
    controller {
      id
    }
    controlledDocument {
      id
    }
    status
  }
  verificationRelationships(
    where: {
      and: [
        { did: $did }
        { notBefore_lte: $timestamp }
        { notAfter_gte: $timestamp }
      ]
    }
  ) {
    id
    name
    vMethodId
    notBefore
    notAfter
  }
  verificationMethods {
    id
    publicKey
    isSecp256k1
    status
  }
}

fragment DidDocumentEvents on DidDocument {
  id
  events(first: $pagesize, skip: $skip) {
    id
    event
    signer
    timestamp
    txId
    blockNumber
  }
}

query GetBlockTimestamp {
  _meta {
    block {
      timestamp
    }
  }
}
