## YAML Template.

version: '2'

networks:
  ebsi_fabricnetwork:
    external: true

services:

  fabricAPi:
    image: ebsi_fabric_api:latest
    container_name: fabric-api
    
    environment:
        
      - CA_URL=http://mspca01-0-fabric-dev-lux.ebsi.xyz:7055
      
      - CA_MSP_ID=EbsiNode1MSP
      
      - PEER_NODE_NAME=peer01-0-fabric-dev-lux.ebsi.xyz
      
      - PEER_NODE_URL=grpcs://peer01-0-fabric-dev-lux.ebsi.xyz:7051
      
      - ORDERER_NODE_NAME=orderer01-0-fabric-dev-lux.ebsi.xyz
      
      - ORDERER_NODE_URL=grpcs://orderer01-0-fabric-dev-lux.ebsi.xyz:7050
      
    ports:
      - 8081:8081
    volumes:
      - ./ssl:/app/ssl/
      - ./src/main/resources/server.jks:/app/server.jks
      #- ./logs:/app/logs/
      - ./wallet:/app/wallet/
    networks:
      ebsi_fabricnetwork:
        aliases:
          - fabric-api