enum HashAlgorithmStatus {
  undefined
  active
  revoked
}

type HashAlgorithm @entity(immutable: false) {
  id: String! # Auto-incremented ID emitted by the smart contract
  ianaName: String!
  multiHash: String!
  oid: String!
  outputLength: BigInt!
  status: HashAlgorithmStatus!
}

# `TimestampedHash` is not immutable because `records` can be mutated
type TimestampedHash @entity(immutable: false) {
  id: Bytes! # Set to `hashValue`
  hashValue: Bytes!
  hashAlgorithm: HashAlgorithm!
  data: Bytes!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  timestampedBy: Bytes! # Address
  transactionHash: Bytes!
  records: [Record!]! # Only useful in the context of timestampVersionHashes
}

# Entity RecordVersion is not immutable because infos can be modified
type RecordVersion @entity(immutable: false) {
  id: Bytes! # Set to `record.id.concat(versionNumber)`
  record: Record!
  versionNumber: BigInt!
  timestamps: [TimestampedHash!]!
  infos: [Bytes!]!
}

type RecordOwner @entity(immutable: false) {
  id: Bytes! # Set to `record.id.concat(ownerId)`
  ownerId: String!
  notBefore: BigInt!
  notAfter: BigInt!
  record: Record!
}

type Record @entity(immutable: true) {
  id: Bytes!
  owners: [RecordOwner!]! @derivedFrom(field: "record")
  versions: [RecordVersion!]! @derivedFrom(field: "record")
}
