enum IssuerType {
  Undefined
  RootTAO
  TAO
  TI
  Revoked
}

type Issuer @entity(immutable: false) {
  id: String!
  attributes: [Attribute!]!
  proxies: [Proxy!]!
}

type Attribute @entity(immutable: false) {
  id: Bytes!
  revisions: [Revision!]!
  lastRevision: Revision!
}

type Revision @entity(immutable: false) {
  id: Bytes!
  data: String!
  issuerType: IssuerType!
  tao: String!
  rootTao: String!
}

type Proxy @entity(immutable: false) {
  id: Bytes!
  data: String!
}

type Metadata @entity(immutable: false) {
  id: Bytes!
  content: String!
}
