version: "3.7"

services:
  notifications-api:
    build: ../..
    image: 305472350643.dkr.ecr.eu-central-1.amazonaws.com/intebsi/notifications-api:integration_ebsiint-2179-deletenotification_v0.0.1
