import {
  Body,
  Controller,
  Get,
  BadRequestException,
  Param,
  Post,
  NotFoundException,
  Response,
  Query,
  UnauthorizedException,
  NotImplementedException,
} from '@nestjs/common';
import {AppService} from './app.service';
import {DIDParams, GovernmentBody, UniversityBody, Document, Accreditation, ChallengeParams} from './validation';
import {AppFormatter} from './app.formatter';
import {ApiOperation, ApiProperty, ApiResponse} from '@nestjs/swagger';

const HTTP_401 = 'The client is not allowed to access resource';
const HTTP_400 = 'Bad Request';
const HTTP_404 = 'Resource not found!';
const HTTP_200 = 'Fetch Resource.';

@Controller('/trusted-issuers-registry')
export class AppController {
  constructor(private appService: AppService, private appFormatter: AppFormatter) {
  }

  @ApiOperation({ description: 'Get all universities defined as trusted issuers in BESU blockchain' })
  @ApiResponse({ status: 200, description: HTTP_200})
  @ApiResponse({ status: 401, description: HTTP_401})

  @Get('/v1/issuers')
  async issuers(@Query() query) {
    try {
      const size = query.page ? query.page.size ?? 10 : 10;
      const after = query.page ? query.page.after ?? 0 : 0;
      let pages;
      const univ = (await this.appService.getUniversityTrustedIssuers()).map((tiUniv) => this.appFormatter.formatUnivIssuer(tiUniv));
      const gov = (await this.appService.getGovTrustedIssuers()).map((tiGov) => this.appFormatter.formatGovIssuer(tiGov));
      let result = {};
      let counter = 0;
      let maxCounter = 0;
      const items = [];
      const itemStartingFrom = after * size;
      for (let i = 0; i < univ.length; i++) {
        counter++;
        if (itemStartingFrom > counter) {
          continue;
        }
        if (maxCounter >= size) {
          continue;
        }
        maxCounter++;
        items.push({
          name:  univ[i].preferredName,
          did: univ[i].issuerDID,
        });
      }
      for (let i = 0; i < gov.length; i++) {
        counter++;
        if (itemStartingFrom >= counter) {
          continue;
        }
        if (maxCounter >= size) {
          continue;
        }
        maxCounter++;
        items.push({
          name:  gov[i].name,
          did: gov[i].issuerDID,
        });

      }
      pages = Math.ceil((counter + 1) / size);
      if ((pages - 1) < after ) {
        throw new BadRequestException('invalid page number');
      }
      result = {
        items,
        total: (counter),
        pageSize: size,
          first: '/trusted-issuers-registry/v1/issuers?page[after]=0&page[size]=' + size,
          prev: '/trusted-issuers-registry/v1/issuers?page[after]=' + Math.max(0, after - 1) +'&page[size]=' + size,
          next: '/trusted-issuers-registry/v1/issuers?page[after]=' + (after - (-1)) + '&page[size]=' + size,
          last: '/trusted-issuers-registry/v1/issuers?page[after]=' + (pages - 1) + '&page[size]=' + size,
      };
      return result;

    } catch (error) {
      throw(error);
    }
  }
  //
  // @ApiOperation({
  //   description: 'Create new university resource and add it to the Trusted issuers. This issuer signs for VA and VP. <br />' +
  //       'The DID is generated by the Wallet from Enterprise Name <br />' +
  //       'The ETH moderator address is currently the wallet address that deployed the smart contracts <br />' +
  //       'In order to authorize please make a GET Request to the challenge API with the university DID that you want to insert and type = universities and create an ETH signature on that message',
  // })
  // @ApiResponse({ status: 201, description: 'University created'})
  // @ApiResponse({ status: 400, description: HTTP_400})
  // @ApiResponse({ status: 401, description: HTTP_401})
  // @Post('/universities')
  // async issuerPost(@Body() body: UniversityBody, @Response() response) {
  //   if (await this.appService.doesIssuerExists(body.issuerDID)) {
  //     throw new BadRequestException('University already exists!');
  //   }
  //   try {
  //     // authorize
  //     const didAuthorized = await this.appService.checkLogin(body.authorize.cryptedMessage, body.authorize.signature, 'universities');
  //     if (didAuthorized !== body.issuerDID) {
  //       throw new UnauthorizedException('you are not authorized to insert for this DID');
  //     }
  //     await this.appService.insertUniversity(body);
  //     response.status(201).send(body);
  //   } catch (Error) {
  //     throw(Error);
  //   }
  // }
  //
  // @ApiOperation({ description: 'Add new document the university can issue to the trusted issuer' })
  // @ApiResponse({ status: 201, description: 'Document added'})
  // @ApiResponse({ status: 400, description: HTTP_401})
  // @ApiResponse({ status: 401, description: HTTP_401})
  // @Post('/universities/:did/documents')
  // async issuerDocumentsPost(@Param() params: DIDParams, @Body() body: Document, @Response() response) {
  //   if (!(await this.appService.doesIssuerExists(params.did))) {
  //     throw new NotFoundException('University does not exist!');
  //   }
  //   try {
  //     await this.appService.addDocumentToIssuer(params.did, body);
  //     response.status(201).send(body);
  //   } catch (Error) {
  //     throw new UnauthorizedException('ether key not found');
  //   }
  // }
  //
  // @ApiOperation({ description: 'Add new Accreditation specifying what an university can issue from trusted issuer point of view' })
  // @ApiResponse({ status: 201, description: 'Accreditation added'})
  // @ApiResponse({ status: 400, description: HTTP_400})
  // @ApiResponse({ status: 401, description: HTTP_401})
  // @Post('/universities/:did/accreditations')
  // async issuerAccreditationsPost(@Param() params: DIDParams, @Body() body: Accreditation, @Response() response) {
  //   if (!(await this.appService.doesIssuerExists(params.did))) {
  //     throw new NotFoundException('University does not exist!');
  //   }
  //   try {
  //     await this.appService.addAccreditationToIssuer(params.did, body);
  //     response.status(201).send(body);
  //   } catch (Error) {
  //     throw new UnauthorizedException('ether key not found');
  //   }
  // }
  //
  // @ApiOperation({
  //   description: 'Create new government resource and add it to the governments trusted issuers. This type of issuer signs for EIDs<br />' +
  //       'The DID is generated by the Wallet from Enterprise Name <br />' +
  //       'The ETH moderator address is currently the wallet address that deployed the smart contracts <br />' +
  //       'In order to authorize please make a GET Request to the challenge API with the university DID that you want to insert and type = governments and create an ETH signature on that message',
  // })  @ApiResponse({ status: 201, description: 'Accreditation added'})
  // @ApiResponse({ status: 400, description: HTTP_400})
  // @ApiResponse({ status: 401, description: HTTP_401})
  // @Post('/governments')
  // async issuerGovPost(@Body() body: GovernmentBody, @Response() response) {
  //   if (await this.appService.doesIssuerForGovExists(body.issuerDID)) {
  //     throw new BadRequestException('Government already exists!');
  //   }
  //   try {
  //     const didAuthorized = await this.appService.checkLogin(body.authorize.cryptedMessage, body.authorize.signature, 'governments');
  //     if (didAuthorized !== body.issuerDID) {
  //       throw new UnauthorizedException('you are not authorized to insert for this DID');
  //     }
  //     await this.appService.insertGovernment(body);
  //     response.status(201).send(body);
  //   } catch (Error) {
  //     throw new UnauthorizedException('ether key not found');
  //   }
  // }
  //
  // @ApiOperation({ description: 'Add document on an already created government entity' })
  // @ApiResponse({ status: 201, description: 'Document added'})
  // @ApiResponse({ status: 400, description: HTTP_400})
  // @ApiResponse({ status: 401, description: HTTP_401})
  // @Post('/governments/:did/documents')
  // async issuerGovernmentsPost(@Param() params: DIDParams, @Body() body: Document, @Response() response) {
  //   if (!(await this.appService.doesIssuerForGovExists(params.did))) {
  //     throw new NotFoundException('Government does not exist!');
  //   }
  //   try {
  //     await this.appService.addGovDocumentToIssuer(params.did, body);
  //     response.status(201).send(body);
  //   } catch (Error) {
  //     throw new UnauthorizedException('ether key not found');
  //   }
  // }

  @ApiOperation({ description: 'Get trusted issuer by did by DID' })
  @ApiResponse({ status: 200, description: 'University JSON'})
  @ApiResponse({ status: 404, description: HTTP_404})
  @ApiResponse({ status: 401, description: HTTP_401})
  @Get('/v1/issuers/:did')
  async issuer(@Param() params: DIDParams) {


    try {
      let univTypeIssuer = {};
      let govTypeIssuer = {};
      if (await this.appService.doesIssuerExists(params.did)) {
        univTypeIssuer = await this.appService.getIssuer(params.did);
      }
      if (await this.appService.doesIssuerForGovExists(params.did)) {
        govTypeIssuer = await this.appService.getIssuerForGov(params.did);
      }
      const result =  {...univTypeIssuer, ...govTypeIssuer};
      if (!Object.keys(result).length) {
        throw new NotFoundException('The format of {did} parameter is not valid or entity not found');
      }
      return result;
    } catch (error) {
      throw(error);
    }

  }
  //
  // @ApiOperation({ description: 'Get government by DID' })
  // @ApiResponse({ status: 200, description: 'Government JSON'})
  // @ApiResponse({ status: 404, description: HTTP_404})
  // @ApiResponse({ status: 401, description: HTTP_401})
  // @Get('/governments/:did')
  // async issuerGov(@Param() params: DIDParams) {
  //   if (!(await this.appService.doesIssuerForGovExists(params.did))) {
  //     throw new NotFoundException('Government does not exist!');
  //   }
  //   const issuer = await this.appService.getIssuerForGov(params.did);
  //   const documents = await this.appService.getDocumentsForGov(params.did);
  //   return {
  //     moderator: issuer.moderator,
  //     issuerDID: issuer.issuerDID,
  //     name: issuer.name,
  //     country: issuer.country,
  //     status: issuer.status,
  //     documents: documents.map((document) => this.appFormatter.formatDocument(document)),
  //   };
  // }
  // @ApiOperation({ description: 'Get challenge to be signed with the eth address' })
  // @ApiResponse({ status: 200, description: 'Government JSON'})
  // @ApiResponse({ status: 404, description: HTTP_404})
  // @ApiResponse({ status: 401, description: HTTP_401})
  // @Get('/challenge/:did/:type')
  // async challenge(@Param() params: ChallengeParams) {
  //   switch (params.type) {
  //     case 'universities':
  //       if ((await this.appService.doesIssuerForGovExists(params.did))) {
  //         throw new NotFoundException('Government does exist!');
  //       }
  //       break;
  //     case 'governments':
  //       if ((await this.appService.doesIssuerExists(params.did))) {
  //         throw new NotFoundException('University does exist!');
  //       }
  //       break;
  //     default:
  //       throw new NotImplementedException('entity not implemented');
  //   }
  //   return this.appService.generateLoginChallenge(params.did, params.type);
  // }
}
