/* eslint-disable operator-linebreak */
/* eslint-disable prettier/prettier */
// CONFIG PROJECT FILE
import * as dotenv from "dotenv";
// importing .env variables
dotenv.config();

const LOCALHOST = "http://localhost";
const EBSI_API_DEV_URL = "https://api.ebsi.xyz";
const EBSI_APP_DEV_URL = "https://app.ebsi.xyz";
const EBSI_API_INT_URL = "https://api.intebsi.xyz";
const EBSI_APP_INT_URL = "https://app.intebsi.xyz";
const ECAS_PROD_URL = "https://ecas.ec.europa.eu/cas";
const EBSI_API_PROD_URL = "https://api.ebsi.tech.ec.europa.eu";
const EBSI_APP_PROD_URL = "https://app.ebsi.tech.ec.europa.eu";
const ECAS_DEV_URL = "https://ecas.acceptance.ec.europa.eu/cas";
const UNIVERSAL_RESOLVER_PATH = "/universal-resolver";
const BESU_SERVICE_PATH = "/blockchain/besu";
const OPENAPI_PATH = "../../api/openapi.yaml";
const API_VERSION = "v1"

// GLOBAL ENVIRONMENT CONFIG AND URLS PER EACH ENV
const GLOBAL_CONFIG = {
  production: {
    logLevel: "info",
    ebsiApiBaseUrl: EBSI_API_PROD_URL,
    ebsiAppBaseUrl: EBSI_APP_PROD_URL,
    walletAppBaseUrl: EBSI_APP_PROD_URL,
    walletAppBasePath: "/wallet",
    walletAppPort: "",
    ecasCasUrl: ECAS_PROD_URL,
    universalResolverUri: EBSI_API_PROD_URL + UNIVERSAL_RESOLVER_PATH,
    besuServiceProvider: EBSI_API_PROD_URL + BESU_SERVICE_PATH,
    idHubExternal: EBSI_API_PROD_URL,
    iccDid: "ebsi:did:TBD",
    walletApiBaseUrl: LOCALHOST,
    ebsiInternalApiBaseUrl: LOCALHOST,
  },
  development: {
    logLevel: "silly",
    ebsiApiBaseUrl: EBSI_API_DEV_URL,
    ebsiAppBaseUrl: EBSI_APP_DEV_URL,
    walletAppBaseUrl: EBSI_APP_DEV_URL,
    walletAppBasePath: "/wallet",
    walletAppPort: "",
    ecasCasUrl: ECAS_PROD_URL,
    universalResolverUri: EBSI_API_DEV_URL + UNIVERSAL_RESOLVER_PATH,
    besuServiceProvider: EBSI_API_DEV_URL + BESU_SERVICE_PATH,
    idHubExternal: EBSI_API_DEV_URL,
    iccDid: "ebsi:did:0xF648c19a1d1de071bc863b115e3feBB7ECe2115B",
    walletApiBaseUrl: LOCALHOST,
    ebsiInternalApiBaseUrl: LOCALHOST,
  },
  integration: {
    logLevel: "silly",
    ebsiApiBaseUrl: EBSI_API_INT_URL,
    ebsiAppBaseUrl: EBSI_APP_INT_URL,
    walletAppBaseUrl: EBSI_APP_INT_URL,
    walletAppBasePath: "/wallet",
    walletAppPort: "",
    ecasCasUrl: ECAS_PROD_URL,
    universalResolverUri: EBSI_API_INT_URL + UNIVERSAL_RESOLVER_PATH,
    besuServiceProvider: EBSI_API_INT_URL + BESU_SERVICE_PATH,
    idHubExternal: EBSI_API_INT_URL,
    iccDid: "did:ebsi:0x559Efd67F7F8228449aD49f449F574D9CaDa2e68",
    walletApiBaseUrl: LOCALHOST,
    ebsiInternalApiBaseUrl: LOCALHOST,
  },
  test: {
    logLevel: "info",
    ebsiApiBaseUrl: EBSI_API_INT_URL,
    ebsiAppBaseUrl: EBSI_APP_INT_URL,
    walletAppBaseUrl: EBSI_APP_INT_URL,
    walletAppBasePath: "/wallet",
    walletAppPort: "",
    ecasCasUrl: ECAS_PROD_URL,
    universalResolverUri: EBSI_API_INT_URL + UNIVERSAL_RESOLVER_PATH,
    besuServiceProvider: EBSI_API_INT_URL + BESU_SERVICE_PATH,
    idHubExternal: EBSI_API_INT_URL,
    iccDid: "did:ebsi:0x559Efd67F7F8228449aD49f449F574D9CaDa2e68",
    walletApiBaseUrl: EBSI_API_INT_URL,
    ebsiInternalApiBaseUrl: EBSI_API_INT_URL,
  },
  local: {
    logLevel: process.env.DEBUG_LEVEL === "silly" ? "silly" : "debug",
    ebsiApiBaseUrl: EBSI_API_INT_URL,
    ebsiAppBaseUrl: EBSI_APP_INT_URL,
    walletAppBaseUrl: LOCALHOST,
    walletAppBasePath: "",
    walletAppPort: `:${process.env.WALLET_APP_PORT || 3000}`,
    ecasCasUrl: ECAS_DEV_URL,
    universalResolverUri: EBSI_API_INT_URL + UNIVERSAL_RESOLVER_PATH,
    besuServiceProvider: EBSI_API_INT_URL + BESU_SERVICE_PATH,
    idHubExternal: `${LOCALHOST}:3009`,
    iccDid: "did:ebsi:0x559Efd67F7F8228449aD49f449F574D9CaDa2e68",
    walletApiBaseUrl: LOCALHOST,
    ebsiInternalApiBaseUrl: LOCALHOST,
  },
};
// eslint-disable-next-line prettier/prettier
const ENVIRONMENT =
  process.env.NODE_ENV === "test" ||
  process.env.NODE_ENV === "production" ||
  process.env.NODE_ENV === "development" ||
  // eslint-disable-next-line prettier/prettier
  process.env.NODE_ENV === "local"
    ? process.env.NODE_ENV
    : "integration"; // integration by default

const FINAL_CONFIG = GLOBAL_CONFIG[ENVIRONMENT];
const LOG_LEVEL = FINAL_CONFIG.logLevel;
const EBSI_DEFAULT_DATA_STORE = "cassandra";

const WALLET_API_BASE_URL = FINAL_CONFIG.walletApiBaseUrl;
const EBSI_INTERNAL_API_BASE_URL = FINAL_CONFIG.ebsiInternalApiBaseUrl;
const ECAS_CAS_URL = FINAL_CONFIG.ecasCasUrl;
const WALLET_APP_BASE_URL = FINAL_CONFIG.walletAppBaseUrl;
const EBSI_EXTERNAL_API_BASE_URL = FINAL_CONFIG.ebsiApiBaseUrl;
const EBSI_UNIVERSAL_RESOLVER_API_URI = FINAL_CONFIG.universalResolverUri;
const BESU_SERVICE_PROVIDER = FINAL_CONFIG.besuServiceProvider;

const EBSI_BASE_PATH = {
  IDHUB: `/identity-hub/${API_VERSION}`,
  ICC: "/company",
  WALLET: "/wallet",
  VERIFIABLE_PRESENTATION: "/verifiable-presentation",
  API_DOCS: "/api-docs",
  NOTARY_API: "/notary",
  UNIVERSITY: "/university",
  DIDDOCUMENT: "/diddocument",
  CREDENTIAL: "/credential",
  VERIFIABLEID: "/verifiableid",
  FILE_STORAGE: "/file-storage",
  EBSI_TRUSTED_APP: "/ebsitrustedapp",
  EBSI_TRUSTED_ISSUERS: "/trusted-issuers",
  KEY_VALUE_STORAGE: "/key-value-storage",
  WALLET_REQUEST_STORAGE: "/wallet-request-storage",
  WALLET_HISTORICAL_STORAGE: "/wallet-historical-storage",
  WALLET_APP: GLOBAL_CONFIG[ENVIRONMENT].walletAppBasePath,
};

const EBSI_SERVICE_NAME = {
  IDHUB: "ID HUB",
  VERIFIABLE_PRESENTATION: "VERIFIABLE PRESENTATION",
  WALLET: "WALLET API",
  APIC_DOCS: "API DOCS",
  NOTARY_API: "NOTARY API",
  CREDENTIAL: "CREDENTIAL",
  UNIVERSITY: "UNIVERSITY",
  WALLET_APP: "WALLET UI APP",
  FILE_STORAGE: "FILE STORAGE",
  VERIFIABLEID: "VERIFIABLE ID",
  ICC: "ITALIAN CHAMBER OF COMMERCE",
  WALLET_DATA_STORE: "DATA STORE WALLET",
  WALLET_AUTHMANAGER: "AUTH MANAGER WALLET",
  WALLET_DIDDOCUMENT: "DID DOCUMENT WALLET",
  WALLET_NOTIFICATIONS: "NOTIFICATIONS WALLET",
  WALLET_SECURE_ENCLAVE: "SECURE ENCLAVE WALLET",
  WALLET_REQUEST_STORAGE: "WALLET REQUEST STORAGE",
};

const EBSI_SERVICE_BASE_URL = {
  WALLET: WALLET_API_BASE_URL,
  WALLET_APP: WALLET_APP_BASE_URL,
  ICC: EBSI_INTERNAL_API_BASE_URL,
  IDHUB: EBSI_INTERNAL_API_BASE_URL,
  VERIFIABLE_PRESENTATION: EBSI_INTERNAL_API_BASE_URL,
  APIC_DOCS: EBSI_EXTERNAL_API_BASE_URL,
  UNIVERSITY: EBSI_INTERNAL_API_BASE_URL,
  CREDENTIAL: EBSI_INTERNAL_API_BASE_URL,
  NOTARY_API: EBSI_EXTERNAL_API_BASE_URL,
  VERIFIABLEID: EBSI_INTERNAL_API_BASE_URL,
  FILE_STORAGE: EBSI_EXTERNAL_API_BASE_URL,
  WALLET_DATA_STORE: EBSI_INTERNAL_API_BASE_URL,
  WALLET_AUTHMANAGER: EBSI_INTERNAL_API_BASE_URL,
  WALLET_DIDDOCUMENT: EBSI_INTERNAL_API_BASE_URL,
  WALLET_NOTIFICATIONS: EBSI_INTERNAL_API_BASE_URL,
  WALLET_SECURE_ENCLAVE: EBSI_INTERNAL_API_BASE_URL,
  KEY_VALUE_STORAGE: EBSI_EXTERNAL_API_BASE_URL,
  TRUSTED_APP_API: EBSI_EXTERNAL_API_BASE_URL,
  WALLET_REQUEST_STORAGE: EBSI_EXTERNAL_API_BASE_URL,
  WALLET_HISTORICAL_STORAGE: EBSI_EXTERNAL_API_BASE_URL,
};

const EBSI_SERVICE_PORT = {
  ICC: 9011,
  IDHUB: 9000,
  WALLET: 3002,
  VERIFIABLE_PRESENTATION: 9012,
  CREDENTIAL: 3008,
  UNIVERSITY: 9010,
  VERIFIABLEID: 3011,
  WALLET_DATA_STORE: 3002 + 8,
  WALLET_AUTHMANAGER: 3002 + 3,
  WALLET_DIDDOCUMENT: 3002 + 4,
  WALLET_NOTIFICATIONS: 3002 + 1,
  WALLET_SECURE_ENCLAVE: 3002 + 2,
  WALLET_APP: FINAL_CONFIG.walletAppPort,
};

const EBSI_SERVICE_SWAGGER = {
  WALLET: EBSI_BASE_PATH.WALLET + EBSI_BASE_PATH.API_DOCS,
  WALLET_DATA_STORE: EBSI_BASE_PATH.WALLET + EBSI_BASE_PATH.API_DOCS,
  WALLET_DIDDOCUMENT: EBSI_BASE_PATH.WALLET + EBSI_BASE_PATH.API_DOCS,
  WALLET_AUTHMANAGER: EBSI_BASE_PATH.WALLET + EBSI_BASE_PATH.API_DOCS,
  WALLET_NOTIFICATIONS: EBSI_BASE_PATH.WALLET + EBSI_BASE_PATH.API_DOCS,
  WALLET_SECURE_ENCLAVE: EBSI_BASE_PATH.WALLET + EBSI_BASE_PATH.API_DOCS,
  ICC: EBSI_BASE_PATH.WALLET + EBSI_BASE_PATH.ICC + EBSI_BASE_PATH.API_DOCS,
  IDHUB: EBSI_BASE_PATH.IDHUB + EBSI_BASE_PATH.API_DOCS,
  VERIFIABLE_PRESENTATION:
    EBSI_BASE_PATH.WALLET +
    EBSI_BASE_PATH.VERIFIABLE_PRESENTATION +
    EBSI_BASE_PATH.API_DOCS,
  CREDENTIAL:
    EBSI_BASE_PATH.WALLET + EBSI_BASE_PATH.CREDENTIAL + EBSI_BASE_PATH.API_DOCS,
  VERIFIABLEID:
    EBSI_BASE_PATH.WALLET +
    EBSI_BASE_PATH.VERIFIABLEID +
    EBSI_BASE_PATH.API_DOCS,
};

const EBSI_SERVICE_CALL = {
  TOKEN: "/token",
  SIGN_TX: "/signtx",
  SEND_TX: "/sendtx",
  EBSI_LOGIN: "/sessions",
  PUBLIC_KEY: "/diddocument/publickey",
  DIPLOMA_CREATION: "",
  COMPANY_CREATION: "",
  API_DOCS: "/api-docs",
  VERIFIABLEID_CREATION: "",
  USER_TOKEN: "/user/token",
  USER_LOGIN: "/user/login",
  ENTERPRISE_LOGIN: "/login",
  DIDDOCUMENT: "/diddocument",
  GET_ATTRIBUTE: "/attributes",
  SET_ATTRIBUTE: "/attributes",
  GET_ATTRIBUTES: "/attributes",
  SIGNATURE_CREATION: "/signature",
  COMPANY_VALIDATION: "/validation",
  DIPLOMA_VALIDATION: "/validation",
  ATTESTATION_CREATION: "/attestation",
  LIST_NOTIFICATIONS: "/notifications",
  PRESENTATION_CREATION: "/presentation",
  VERIFIABLEID_VALIDATION: "/validation",
  NOTIFICATION_CREATION: "/notification",
  ACCEPT_NOTIFICATION: "/notification/accept",
  SIGNATURE_VALIDATION: "/signature/validation",
  ATTESTATION_VALIDATION: "/attestation/validation",
  LATEST_NOTIFICATION_ID: "/latest-notification-id",
  CREDENTIAL_VERIFIABLEID_CREATION: "/verifiableid",
  PRESENTATION_VALIDATION: "/presentation/validation",
  CREDENTIAL_VERIFIABLEID_VALIDATION: "/verifiableid/validation",
  CREDENTIAL_PRESENTATION_VALIDATION: "/presentation/validation",
  CREDENTIAL_PRESENTATION_CREATION: "/presentation",
  PRESENTATION_NOTIFICATION_CREATION: "/presentation/notification",
  CREDENTIAL_PRESENTATION_NOTIFICATION_CREATION: "/presentation/notification",
};

const EBSI_SERVICE_URL = {
  APIC_DOCS: EBSI_SERVICE_BASE_URL.APIC_DOCS + EBSI_BASE_PATH.API_DOCS,
  NOTARY_API: EBSI_SERVICE_BASE_URL.NOTARY_API + EBSI_BASE_PATH.NOTARY_API,
  FILE_STORAGE:
    EBSI_SERVICE_BASE_URL.FILE_STORAGE + EBSI_BASE_PATH.FILE_STORAGE,
  KEY_VALUE_STORAGE:
    EBSI_SERVICE_BASE_URL.FILE_STORAGE + EBSI_BASE_PATH.KEY_VALUE_STORAGE,
  TRUSTED_APP_API:
    EBSI_SERVICE_BASE_URL.TRUSTED_APP_API + EBSI_BASE_PATH.EBSI_TRUSTED_APP,
  TRUSTED_ISSUERS_API:
    EBSI_SERVICE_BASE_URL.TRUSTED_APP_API + EBSI_BASE_PATH.EBSI_TRUSTED_ISSUERS,
  WALLET:
    ENVIRONMENT === "test"
      ? EBSI_SERVICE_BASE_URL.WALLET + EBSI_BASE_PATH.WALLET
      : `${EBSI_SERVICE_BASE_URL.WALLET}:${EBSI_SERVICE_PORT.WALLET}${EBSI_BASE_PATH.WALLET}`,
  ICC:
    ENVIRONMENT === "test"
      ? EBSI_SERVICE_BASE_URL.ICC + EBSI_BASE_PATH.WALLET + EBSI_BASE_PATH.ICC
      : `${EBSI_SERVICE_BASE_URL.ICC}:${EBSI_SERVICE_PORT.ICC}${EBSI_BASE_PATH.WALLET}${EBSI_BASE_PATH.ICC}`,
  WALLET_REQUEST_STORAGE:
    EBSI_SERVICE_BASE_URL.WALLET_REQUEST_STORAGE +
    EBSI_BASE_PATH.WALLET_REQUEST_STORAGE,
  WALLET_APP:
    EBSI_SERVICE_BASE_URL.WALLET_APP +
    EBSI_SERVICE_PORT.WALLET_APP +
    EBSI_BASE_PATH.WALLET_APP,
  IDHUB:
    ENVIRONMENT === "test"
      ? EBSI_SERVICE_BASE_URL.IDHUB +
        EBSI_BASE_PATH.IDHUB
      : `${EBSI_SERVICE_BASE_URL.IDHUB}:${EBSI_SERVICE_PORT.IDHUB}${EBSI_BASE_PATH.IDHUB}`,
  WALLET_HISTORICAL_STORAGE:
    EBSI_SERVICE_BASE_URL.WALLET_REQUEST_STORAGE +
    EBSI_BASE_PATH.WALLET_HISTORICAL_STORAGE,
  VERIFIABLE_PRESENTATION:
    ENVIRONMENT === "test"
      ? EBSI_SERVICE_BASE_URL.VERIFIABLE_PRESENTATION +
        EBSI_BASE_PATH.WALLET +
        EBSI_BASE_PATH.VERIFIABLE_PRESENTATION
      : `${EBSI_SERVICE_BASE_URL.VERIFIABLE_PRESENTATION}:${EBSI_SERVICE_PORT.VERIFIABLE_PRESENTATION}${EBSI_BASE_PATH.WALLET}${EBSI_BASE_PATH.VERIFIABLE_PRESENTATION}`,
  WALLET_DATA_STORE:
    ENVIRONMENT === "test"
      ? EBSI_SERVICE_BASE_URL.WALLET_DATA_STORE + EBSI_BASE_PATH.WALLET
      : `${EBSI_SERVICE_BASE_URL.WALLET_DATA_STORE}:${EBSI_SERVICE_PORT.WALLET_DATA_STORE}${EBSI_BASE_PATH.WALLET}`,
  WALLET_AUTHMANAGER:
    ENVIRONMENT === "test"
      ? EBSI_SERVICE_BASE_URL.WALLET_AUTHMANAGER + EBSI_BASE_PATH.WALLET
      : `${EBSI_SERVICE_BASE_URL.WALLET_AUTHMANAGER}:${EBSI_SERVICE_PORT.WALLET_AUTHMANAGER}${EBSI_BASE_PATH.WALLET}`,
  WALLET_DIDDOCUMENT:
    ENVIRONMENT === "test"
      ? EBSI_SERVICE_BASE_URL.WALLET_DIDDOCUMENT + EBSI_BASE_PATH.WALLET
      : `${EBSI_SERVICE_BASE_URL.WALLET_DIDDOCUMENT}:${EBSI_SERVICE_PORT.WALLET_DIDDOCUMENT}${EBSI_BASE_PATH.WALLET}`,
  UNIVERSITY:
    ENVIRONMENT === "test"
      ? EBSI_SERVICE_BASE_URL.UNIVERSITY +
        EBSI_BASE_PATH.WALLET +
        EBSI_BASE_PATH.UNIVERSITY
      : `${EBSI_SERVICE_BASE_URL.UNIVERSITY}:${EBSI_SERVICE_PORT.UNIVERSITY}${EBSI_BASE_PATH.WALLET}${EBSI_BASE_PATH.UNIVERSITY}`,
  CREDENTIAL:
    ENVIRONMENT === "test"
      ? EBSI_SERVICE_BASE_URL.CREDENTIAL +
        EBSI_BASE_PATH.WALLET +
        EBSI_BASE_PATH.CREDENTIAL
      : `${EBSI_SERVICE_BASE_URL.CREDENTIAL}:${EBSI_SERVICE_PORT.CREDENTIAL}${EBSI_BASE_PATH.WALLET}${EBSI_BASE_PATH.CREDENTIAL}`,
  WALLET_NOTIFICATIONS:
    ENVIRONMENT === "test"
      ? EBSI_SERVICE_BASE_URL.WALLET_NOTIFICATIONS +
        EBSI_BASE_PATH.WALLET +
        EBSI_BASE_PATH.WALLET
      : `${EBSI_SERVICE_BASE_URL.WALLET_NOTIFICATIONS}:${EBSI_SERVICE_PORT.WALLET_NOTIFICATIONS}${EBSI_BASE_PATH.WALLET}`,
  WALLET_SECURE_ENCLAVE:
    ENVIRONMENT === "test"
      ? EBSI_SERVICE_BASE_URL.WALLET_SECURE_ENCLAVE + EBSI_BASE_PATH.WALLET
      : `${EBSI_SERVICE_BASE_URL.WALLET_SECURE_ENCLAVE}:${EBSI_SERVICE_PORT.WALLET_SECURE_ENCLAVE}${EBSI_BASE_PATH.WALLET}`,
  VERIFIABLEID:
    ENVIRONMENT === "test"
      ? EBSI_SERVICE_BASE_URL.VERIFIABLEID +
        EBSI_BASE_PATH.WALLET +
        EBSI_BASE_PATH.VERIFIABLEID
      : `${EBSI_SERVICE_BASE_URL.VERIFIABLEID}:${EBSI_SERVICE_PORT.VERIFIABLEID}${EBSI_BASE_PATH.WALLET}${EBSI_BASE_PATH.VERIFIABLEID}`,
};

const EBSI_SERVICE_SWAGGER_FULL_URL = {
  ICC: EBSI_SERVICE_URL.ICC + EBSI_BASE_PATH.API_DOCS,
  IDHUB: EBSI_SERVICE_URL.IDHUB + EBSI_BASE_PATH.API_DOCS,
  WALLET: EBSI_SERVICE_URL.WALLET + EBSI_BASE_PATH.API_DOCS,
  VERIFIABLE_PRESENTATION:
    EBSI_SERVICE_URL.VERIFIABLE_PRESENTATION + EBSI_BASE_PATH.API_DOCS,
  CREDENTIAL: EBSI_SERVICE_URL.CREDENTIAL + EBSI_BASE_PATH.API_DOCS,
  VERIFIABLEID: EBSI_SERVICE_URL.VERIFIABLEID + EBSI_BASE_PATH.API_DOCS,
  WALLET_DATA_STORE:
    EBSI_SERVICE_URL.WALLET_DATA_STORE + EBSI_BASE_PATH.API_DOCS,
  WALLET_DIDDOCUMENT:
    EBSI_SERVICE_URL.WALLET_DIDDOCUMENT + EBSI_BASE_PATH.API_DOCS,
  WALLET_AUTHMANAGER:
    EBSI_SERVICE_URL.WALLET_AUTHMANAGER + EBSI_BASE_PATH.API_DOCS,
  WALLET_NOTIFICATIONS:
    EBSI_SERVICE_URL.WALLET_NOTIFICATIONS + EBSI_BASE_PATH.API_DOCS,
  WALLET_SECURE_ENCLAVE:
    EBSI_SERVICE_URL.WALLET_SECURE_ENCLAVE + EBSI_BASE_PATH.API_DOCS,
};

const EBSI_SERVICE_EXTERNAL_SWAGGER_FULL_URL = {
  WALLET:
    EBSI_EXTERNAL_API_BASE_URL +
    EBSI_BASE_PATH.WALLET +
    EBSI_BASE_PATH.API_DOCS,
  ICC:
    EBSI_EXTERNAL_API_BASE_URL +
    EBSI_BASE_PATH.WALLET +
    EBSI_BASE_PATH.ICC +
    EBSI_BASE_PATH.API_DOCS,
  IDHUB:
    EBSI_EXTERNAL_API_BASE_URL +
    EBSI_BASE_PATH.WALLET +
    EBSI_BASE_PATH.IDHUB +
    EBSI_BASE_PATH.API_DOCS,
  VERIFIABLE_PRESENTATION:
    EBSI_EXTERNAL_API_BASE_URL +
    EBSI_BASE_PATH.WALLET +
    EBSI_BASE_PATH.VERIFIABLE_PRESENTATION +
    EBSI_BASE_PATH.API_DOCS,
  CREDENTIAL:
    EBSI_EXTERNAL_API_BASE_URL +
    EBSI_BASE_PATH.WALLET +
    EBSI_BASE_PATH.CREDENTIAL +
    EBSI_BASE_PATH.API_DOCS,
  VERIFIABLEID:
    EBSI_EXTERNAL_API_BASE_URL +
    EBSI_BASE_PATH.WALLET +
    EBSI_BASE_PATH.VERIFIABLEID +
    EBSI_BASE_PATH.API_DOCS,
};

const EBSI_SERVICE = {
  NAME: EBSI_SERVICE_NAME,
  BASE_URL: EBSI_SERVICE_BASE_URL,
  PORT: EBSI_SERVICE_PORT,
  SWAGGER: EBSI_SERVICE_SWAGGER,
  CALL: EBSI_SERVICE_CALL,
  URL: EBSI_SERVICE_URL,
  BASE_PATH: EBSI_BASE_PATH,
  SWAGGER_FULL_URL: EBSI_SERVICE_SWAGGER_FULL_URL,
  EXTERNAL_SWAGGER_FULL_URL: EBSI_SERVICE_EXTERNAL_SWAGGER_FULL_URL,
};
// variable to set the access to TRUSTED_APP API
const EBSI_TRUSTED_APP_API_URI = EBSI_SERVICE.URL.TRUSTED_APP_API;

enum EBSI_APPS {
  BESU = "ebsi-besu",
  IDHUB = "ebsi-idhub",
  WALLET = "ebsi-wallet",
  STORAGE = "ebsi-storage",
  FILE_STORAGE = "ebsi-storage",
  KEY_VALUE_STORAGE = "ebsi-storage",
  REQUEST_QUEUE_STORAGE = "ebsi-storage",
  HISTORICAL_QUEUE_STORAGE = "ebsi-storage",
}

const EBSI_API_MAP = new Map<string, string>([
  [EBSI_APPS.BESU, BESU_SERVICE_PROVIDER],
  [EBSI_APPS.WALLET, EBSI_SERVICE.URL.WALLET],
  [EBSI_APPS.STORAGE, EBSI_SERVICE.URL.FILE_STORAGE],
  [EBSI_APPS.IDHUB, EBSI_SERVICE.URL.IDHUB],
]);

export enum EBSI_DATA_STORE_TYPE {
  FILE_STORAGE,
  KEY_VALUE_STORAGE,
  REQUEST_QUEUE_STORAGE,
  HISTORICAL_QUEUE_STORAGE,
}

export enum WALLET_DATA_STORE_TYPE {
  CREDINFOLIST_STORAGE,
  DOCINFOLIST_STORAGE,
  ENTERPRISEUSER_STORAGE,
  KEYS_STORAGE,
  UDID_STORAGE,
  USER_STORAGE,
  DOCUMENTFILE_STORAGE,
  CREDENTIALFILE_STORAGE,
  HISTORIALQUEUE_STORAGE,
  REQUESTQUEUE_STORAGE,
}

const WALLET_DATA_STORE_TYPE_MAP = new Map<number, number>([
  [WALLET_DATA_STORE_TYPE.KEYS_STORAGE, EBSI_DATA_STORE_TYPE.KEY_VALUE_STORAGE],
  [WALLET_DATA_STORE_TYPE.UDID_STORAGE, EBSI_DATA_STORE_TYPE.KEY_VALUE_STORAGE],
  [WALLET_DATA_STORE_TYPE.USER_STORAGE, EBSI_DATA_STORE_TYPE.KEY_VALUE_STORAGE],
  [
    WALLET_DATA_STORE_TYPE.DOCUMENTFILE_STORAGE,
    EBSI_DATA_STORE_TYPE.FILE_STORAGE,
  ],
  [
    WALLET_DATA_STORE_TYPE.CREDENTIALFILE_STORAGE,
    EBSI_DATA_STORE_TYPE.FILE_STORAGE,
  ],
  [
    WALLET_DATA_STORE_TYPE.DOCINFOLIST_STORAGE,
    EBSI_DATA_STORE_TYPE.KEY_VALUE_STORAGE,
  ],
  [
    WALLET_DATA_STORE_TYPE.CREDINFOLIST_STORAGE,
    EBSI_DATA_STORE_TYPE.KEY_VALUE_STORAGE,
  ],
  [
    WALLET_DATA_STORE_TYPE.ENTERPRISEUSER_STORAGE,
    EBSI_DATA_STORE_TYPE.KEY_VALUE_STORAGE,
  ],
  [
    WALLET_DATA_STORE_TYPE.REQUESTQUEUE_STORAGE,
    EBSI_DATA_STORE_TYPE.REQUEST_QUEUE_STORAGE,
  ],
  [
    WALLET_DATA_STORE_TYPE.HISTORIALQUEUE_STORAGE,
    EBSI_DATA_STORE_TYPE.HISTORICAL_QUEUE_STORAGE,
  ],
]);

const WALLET_DATA_STORE_CONFIG_MAP = new Map<number, [string, string]>([
  [
    EBSI_DATA_STORE_TYPE.FILE_STORAGE,
    [EBSI_SERVICE.URL.FILE_STORAGE, EBSI_APPS.FILE_STORAGE],
  ],
  [
    EBSI_DATA_STORE_TYPE.KEY_VALUE_STORAGE,
    [EBSI_SERVICE.URL.KEY_VALUE_STORAGE, EBSI_APPS.KEY_VALUE_STORAGE],
  ],
  [
    EBSI_DATA_STORE_TYPE.REQUEST_QUEUE_STORAGE,
    [EBSI_SERVICE.URL.WALLET_REQUEST_STORAGE, EBSI_APPS.REQUEST_QUEUE_STORAGE],
  ],
  [
    EBSI_DATA_STORE_TYPE.HISTORICAL_QUEUE_STORAGE,
    [
      EBSI_SERVICE.URL.WALLET_HISTORICAL_STORAGE,
      EBSI_APPS.HISTORICAL_QUEUE_STORAGE,
    ],
  ],
]);

enum WALLET_DATASTORE_CONFIG {
  URI,
  EBSI_APP_NAME,
}

const besu = {
  provider: BESU_SERVICE_PROVIDER,
  didRegistry: process.env.DID_REGISTRY_SC_ADDRESS?.includes("0x")
    ? process.env.DID_REGISTRY_SC_ADDRESS
    : `0x${process.env.DID_REGISTRY_SC_ADDRESS}`,
};

const notary = {
  provider: BESU_SERVICE_PROVIDER,
  notaryAddress: process.env.NOTARY_SC_ADDRESS?.includes("0x")
    ? process.env.NOTARY_SC_ADDRESS
    : `0x${process.env.NOTARY_SC_ADDRESS}`,
};

const KEY_PASSPHRASE = process.env.KEY_PASSPHRASE || "no default password";
const API_NAME = EBSI_APPS.IDHUB;
const trustedAppsRegistry = `${EBSI_EXTERNAL_API_BASE_URL}/trusted-apps-registry/v1`;
const COMPONENT_PASSWORD =
  process.env.COMPONENT_PASSWORD || "no default password";
const COMPONENT_KEYSTORE =
  process.env.COMPONENT_KEYSTORE || "no default key provider";

export {
  besu,
  notary,
  API_NAME,
  LOG_LEVEL,
  EBSI_APPS,
  ENVIRONMENT,
  EBSI_API_MAP,
  ECAS_CAS_URL,
  EBSI_SERVICE,
  OPENAPI_PATH,
  KEY_PASSPHRASE,
  COMPONENT_PASSWORD,
  COMPONENT_KEYSTORE,
  trustedAppsRegistry,
  EBSI_DEFAULT_DATA_STORE,
  WALLET_DATASTORE_CONFIG,
  EBSI_TRUSTED_APP_API_URI,
  WALLET_DATA_STORE_TYPE_MAP,
  WALLET_DATA_STORE_CONFIG_MAP,
  EBSI_UNIVERSAL_RESOLVER_API_URI,
};
