openapi: 3.1.0
info:
  title: Users Onboarding API v2
  version: 2.0.0
  description: |
    Users Onboarding API is an EBSI core service to enable users (Natural Persons and Legal
    Entities) to obtain long-term access to the EBSI network.
  termsOfService: https://api-pilot.ebsi.eu/docs/terms
  contact:
    name: EBSI Support - Service Desk
    url: https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/11
  license:
    name: EUPL-1.2
    url: https://joinup.ec.europa.eu/page/eupl-text-11-12
paths:
  /users-onboarding/v2/sessions:
    post:
      operationId: post-users-onboarding-api-sessions
      summary: Sessions
      description: The endpoint validates the EU Login/reCAPTCHA response and returns a session token.
      requestBody:
        required: true
        description: |
          It requires to provide either the EU Login or reCAPTCHA response.
        content:
          application/json:
            schema:
              type: object
              properties:
                onboarding:
                  description: Either EU Login or reCAPTCHA.
                  type: string
                info:
                  description: Additional onboarding information
                  type: object
            examples:
              EULogin:
                value:
                  onboarding: eu-login
                  info:
                    eul-ticket: EU Login ticket number
              reCAPTCHA:
                value:
                  onboarding: recaptcha
                  info:
                    token: 03AGdBq24EL3Pvtf6wNbAoBHFbrgYCbFQrAtOUTN80C_OTgo5UmdYXXbQwEBzWXpZdHvV18kqy2X3ZO5MjYI7-48aEuzaUSi0d4cyssNOrEDhnQ6Fwkw_nPCsOvqn66_8KSjWAFJWcVSDZYiEa3N8cAuPtisha65ypOSQZGTQO8OtvmX3ots3_3Lg0RYE0FR8nmSHvprBzepB_bNRgIkzFyMQLrWCwT1DIxNlG26fbsYqgHTlqc5_XmLovWoUldx_gptqfsqVw5OhCsf4T_sMSESS6FmNYf_5wW_LLdvtTNcTuENfKFzpJWgTNCrUo7jyBKLJQiuo6d6D0mwO3oWx9JJ2h6cGSRqtMukW5kdO_0kuZ2O7mFKkMo_Godnhf3iHTcNqfIHKvd7hoUbb21SOiLNv4gdQ2v0WyhnZGbPPgGaltpTV5UgboUrCAxhwCsQecjKhW10WAzBaw
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  Bearer:
                    type: string
                    description: Session token
              examples:
                Success:
                  value:
                    Bearer: eyJhbGciOiJFUzI1NiIsImN0eSI6IkpXVCIsImtpZCI6IiIsInR5cCI6IkpXVCJ9.eyJhdEhhc2giOiI4Rlo1YzdROTlWaldETU14Nis4WUt2dTVVTVNuQWpwdWFzSDg1L1JUb3M0PSIsImV4cCI6MTYxNjU3NjEyMCwiaWF0IjoxNjE2NTc2MDAwLCJpc3MiOiJVc2VycyBPbmJvYXJkaW5nIEFQSSIsIm5vbmNlIjoiMDRhYjEzNzUtMGU1MS00YjUyLWE4NTUtM2UxYmY3NWJkOTViIiwic3ViIjoiVXNlcnMgT25ib2FyZGluZyBBUEkifQ.BWfmeyyyN-4CruvkBYOQahsWH5TZEpFn8FU1BY6iazVuxpz2QccN6KEOhIzTDV_cy-lKb64vDO2YjAzcMfJfaw
        "400":
          $ref: "#/components/responses/400"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /users-onboarding/v2/authentication-requests:
    post:
      summary: Authentication requests
      description: The user performs a request to this endpoint to start DID SIOP by requesting the creation of the request. The endpoint returns a DID SIOP authentication request.
      operationId: post-users-onboarding-api-authentication-requests
      parameters:
        - $ref: "#/components/parameters/conformanceHeader"
      requestBody:
        required: true
        description: |
          It requires the following field to be set as:
          - **scope**: ebsi users onboarding
        content:
          application/json:
            schema:
              type: object
              properties:
                scope:
                  description: scope of DID SIOP
                  type: string
            examples:
              request:
                summary: Request Verifiable Authorisation
                value:
                  scope: ebsi users onboarding
      responses:
        "201":
          description: Success - The service (wallet) can request a Verifiable Authorisation
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_token:
                    type: string
                    description: authentication request result
              examples:
                Success:
                  value:
                    session_token: "openid://?response_type=id_token&client_id=https%3A%2F%2Fapi-pilot.ebsi.eu%2Fusers-onboarding%2Fv2%2Fauthentication-responses&scope=openid+did_authn&nonce=0d606dc1-c5a0-4186-a894-5ca998e516d5&request=eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QiLCJraWQiOiJodHRwczovL2FwaS1waWxvdC5lYnNpLmV1L3RydXN0ZWQtYXBwcy1yZWdpc3RyeS92My9hcHBzL3VzZXJzLW9uYm9hcmRpbmctYXBpX3BpbG90LXRlbXAtMDEifQ.eyJzY29wZSI6Im9wZW5pZCBkaWRfYXV0aG4iLCJyZXNwb25zZV90eXBlIjoiaWRfdG9rZW4iLCJyZXNwb25zZV9tb2RlIjoicG9zdCIsImNsaWVudF9pZCI6Imh0dHBzOi8vYXBpLXBpbG90LmVic2kuZXUvdXNlcnMtb25ib2FyZGluZy92Mi9hdXRoZW50aWNhdGlvbi1yZXNwb25zZXMiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL2FwaS1waWxvdC5lYnNpLmV1L3VzZXJzLW9uYm9hcmRpbmcvdjIvYXV0aGVudGljYXRpb24tcmVzcG9uc2VzIiwibm9uY2UiOiIwZDYwNmRjMS1jNWEwLTQxODYtYTg5NC01Y2E5OThlNTE2ZDUiLCJpYXQiOjE2NzI5MDgyNjMsImlzcyI6InVzZXJzLW9uYm9hcmRpbmctYXBpX3BpbG90LXRlbXAtMDEiLCJleHAiOjE2NzI5MDg1NjN9.FJRjA2fsVJeuyLqhmVZw0NcWdM5bKUFORKmr7UGogfGHOiaabxRJsgy0qNkR9pPuZ1MXXdSXHtulcMZxLGgTEg"
        "400":
          $ref: "#/components/responses/400"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /users-onboarding/v2/authentication-responses:
    post:
      summary: Authentication responses
      description: The user performs a request to this endpoint. The Users Onboarding API accepts his/her authentication response, validates it and returns a Verifiable Authorisation.
      operationId: post-users-onboarding-api-authentication-responses
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/conformanceHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: DID Authentication ID Token
              type: object
              properties:
                id_token:
                  description: |
                    DID Auth ID token (JWT) created by the user candidate to be validated.

                    Its header must contain the signer's `kid` (e.g. `"kid": "did:ebsi:zbM8cCuoBMFNLeQyLiVFyxw#keys-1"`).
                    The ID Token payload must contain the following fields:
                    - `aud`: the URL of the /authentication-responses endpoint, e.g. "https://api-pilot.ebsi.eu/users-onboarding/v2/authentication-responses"
                    - `sub`: the subject, e.g. "x8pW2jUNE9ipd3DGgO_D0mUoG1pO1U3fEiqizt9gntQ"
                    - `sub_jwk`: the JWK used to sign the JWT
                    - `nonce`: a random UUID
                    - `responseMode`: should be "form_post",
                    - `iss`: should be "https://self-issued.me/v2",
                  type: string
              required:
                - id_token
            examples:
              request:
                summary: Request Verifiable Authorisation
                value:
                  id_token: eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QiLCJraWQiOiJkaWQ6ZWJzaTp6Yk04Y0N1b0JNRk5MZVF5TGlWRnl4dyNrZXlzLTEifQ.eyJhdWQiOiJodHRwczovL2FwaS1waWxvdC5lYnNpLmV1L3VzZXJzLW9uYm9hcmRpbmcvdjIvYXV0aGVudGljYXRpb24tcmVzcG9uc2VzIiwic3ViIjoieDhwVzJqVU5FOWlwZDNER2dPX0QwbVVvRzFwTzFVM2ZFaXFpenQ5Z250USIsInN1Yl9qd2siOnsia3R5IjoiRUMiLCJ4IjoiRXA5T01UYXl2YnJKWllyQl9xclMtZTZKWE5BVmJHQWhTMThFMDlMb3M2ZyIsInkiOiJtdTVrZnBjZGJHN1JMQWowY2xFZzA1czd5aGR4UTJkNmJTd3c0UkJXcVdVIiwiY3J2Ijoic2VjcDI1NmsxIn0sIm5vbmNlIjoiN2I3OWI5NGMtOTkyZS00YjJkLWJlNjEtODcwZjg5OTliMmUxIiwicmVzcG9uc2VNb2RlIjoiZm9ybV9wb3N0IiwiaWF0IjoxNjcyOTA5MjYyLCJpc3MiOiJodHRwczovL3NlbGYtaXNzdWVkLm1lL3YyIiwiZXhwIjoxNjcyOTA5NTYyfQ.GHSOPdrcltFfKg0ciYE4LrhyDrcaLzhngv4UuXvgaLQFT3592wNkI8lQ-UFKVxzPmZMS0ZEvred8Z9koch4ksg
          application/x-www-form-urlencoded:
            schema:
              title: DID Authentication ID Token
              type: object
              properties:
                id_token:
                  description: |
                    DID Auth ID token (JWT) created by the user candidate to be validated.

                    Its header must contain the signer's `kid` (e.g. `"kid": "did:ebsi:zbM8cCuoBMFNLeQyLiVFyxw#keys-1"`).
                    The ID Token payload must contain the following fields:
                    - `aud`: the URL of the /authentication-responses endpoint, e.g. "https://api-pilot.ebsi.eu/users-onboarding/v2/authentication-responses"
                    - `sub`: the subject, e.g. "x8pW2jUNE9ipd3DGgO_D0mUoG1pO1U3fEiqizt9gntQ"
                    - `sub_jwk`: the JWK used to sign the JWT
                    - `nonce`: a random UUID
                    - `responseMode`: should be "form_post",
                    - `iss`: should be "https://self-issued.me/v2",
                  type: string
              required:
                - id_token
            example:
              id_token: eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QiLCJraWQiOiJkaWQ6ZWJzaTp6Yk04Y0N1b0JNRk5MZVF5TGlWRnl4dyNrZXlzLTEifQ.eyJhdWQiOiJodHRwczovL2FwaS1waWxvdC5lYnNpLmV1L3VzZXJzLW9uYm9hcmRpbmcvdjIvYXV0aGVudGljYXRpb24tcmVzcG9uc2VzIiwic3ViIjoieDhwVzJqVU5FOWlwZDNER2dPX0QwbVVvRzFwTzFVM2ZFaXFpenQ5Z250USIsInN1Yl9qd2siOnsia3R5IjoiRUMiLCJ4IjoiRXA5T01UYXl2YnJKWllyQl9xclMtZTZKWE5BVmJHQWhTMThFMDlMb3M2ZyIsInkiOiJtdTVrZnBjZGJHN1JMQWowY2xFZzA1czd5aGR4UTJkNmJTd3c0UkJXcVdVIiwiY3J2Ijoic2VjcDI1NmsxIn0sIm5vbmNlIjoiN2I3OWI5NGMtOTkyZS00YjJkLWJlNjEtODcwZjg5OTliMmUxIiwicmVzcG9uc2VNb2RlIjoiZm9ybV9wb3N0IiwiaWF0IjoxNjcyOTA5MjYyLCJpc3MiOiJodHRwczovL3NlbGYtaXNzdWVkLm1lL3YyIiwiZXhwIjoxNjcyOTA5NTYyfQ.GHSOPdrcltFfKg0ciYE4LrhyDrcaLzhngv4UuXvgaLQFT3592wNkI8lQ-UFKVxzPmZMS0ZEvred8Z9koch4ksg
      responses:
        "201":
          description: Success - The service (wallet) can prove DID key possession.
          content:
            application/json:
              schema:
                type: object
                properties:
                  verifiableCredential:
                    type: string
                    description: |
                      This field contains the Verifiable Credential requested, i.e. the Verifiable
                      Authorisation, as a VC JWT.
              examples:
                Success:
                  value:
                    verifiableCredential: eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QiLCJraWQiOiJkaWQ6ZWJzaTp6cjJyV0RISHJVQ2RaQVc3d3NTYjVuUSNrZXlzLTEifQ.eyJqdGkiOiJ2YzplYnNpOmF1dGhlbnRpY2F0aW9uIzNmZjJlY2QzLWEwMWMtNDgwOC1iMDY5LTU2NjY5MDI2NjdmNCIsInN1YiI6ImRpZDplYnNpOnpiTThjQ3VvQk1GTkxlUXlMaVZGeXh3IiwiaXNzIjoiZGlkOmVic2k6enIycldESEhyVUNkWkFXN3dzU2I1blEiLCJuYmYiOjE2NzI5MDkyNjMsImV4cCI6MTY4ODYzNDA2MywiaWF0IjoxNjcyOTA5MjYzLCJ2YyI6eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSJdLCJpZCI6InZjOmVic2k6YXV0aGVudGljYXRpb24jM2ZmMmVjZDMtYTAxYy00ODA4LWIwNjktNTY2NjkwMjY2N2Y0IiwidHlwZSI6WyJWZXJpZmlhYmxlQ3JlZGVudGlhbCIsIlZlcmlmaWFibGVBdXRob3Jpc2F0aW9uIl0sImlzc3VlciI6ImRpZDplYnNpOnpyMnJXREhIclVDZFpBVzd3c1NiNW5RIiwiaXNzdWFuY2VEYXRlIjoiMjAyMy0wMS0wNVQwOTowMTowM1oiLCJpc3N1ZWQiOiIyMDIzLTAxLTA1VDA5OjAxOjAzWiIsInZhbGlkRnJvbSI6IjIwMjMtMDEtMDVUMDk6MDE6MDNaIiwiZXhwaXJhdGlvbkRhdGUiOiIyMDIzLTA3LTA2VDA5OjAxOjAzWiIsImNyZWRlbnRpYWxTdWJqZWN0Ijp7ImlkIjoiZGlkOmVic2k6emJNOGNDdW9CTUZOTGVReUxpVkZ5eHcifSwiY3JlZGVudGlhbFNjaGVtYSI6eyJpZCI6Imh0dHBzOi8vYXBpLXBpbG90LmVic2kuZXUvdHJ1c3RlZC1zY2hlbWFzLXJlZ2lzdHJ5L3YyL3NjaGVtYXMvekhNcDUyTHFKV29jbWhBOVJrem5UV3VFZWNKWG9QREt3M2tXUXA4MVlZOXBDIiwidHlwZSI6IkZ1bGxKc29uU2NoZW1hVmFsaWRhdG9yMjAyMSJ9fX0.1jngGGWZF9W8AJXrzJkiscqI9BSsrJIejwsWnyhztAtiG7Ym5ZT9NlHNnSCV9zDrWDOO5idLUuaW5T0gZyYBXw
        "400":
          $ref: "#/components/responses/400"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
components:
  schemas:
    ProblemDetails:
      title: Problem Details
      description: A [Problem Details](https://datatracker.ietf.org/doc/html/rfc7807) object.
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type. When dereferenced, it SHOULD provide human-readable documentation for the problem type.
          default: about:blank
        title:
          type: string
          description: A short summary of the problem type.
          example: Internal Server Error
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 400
          maximum: 600
          example: 500
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the problem.
          example: Connection timeout
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem. It may or may
            not yield further information if dereferenced.
  responses:
    "400":
      description: Bad Request
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
          examples:
            Bad Request:
              $ref: "#/components/examples/BadRequest"
    "404":
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
          examples:
            Not Found:
              $ref: "#/components/examples/NotFound"
    "500":
      description: Internal Error
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
          examples:
            Internal Server Error:
              $ref: "#/components/examples/InternalError"
  examples:
    BadRequest:
      value:
        title: Bad Request
        status: 400
        detail: Bad request.
    NotFound:
      value:
        title: Not Found
        status: 404
        detail: Not found
    InternalError:
      value:
        title: Internal Server Error
        status: 500
        detail: The server encountered an internal error and was unable to process your request.
  parameters:
    conformanceHeader:
      in: header
      name: Conformance
      description: |
        Conformance test UUID. UUID V4 should be used. The header is
        required when running the conformance tests to log the activities.
      required: false
      schema:
        type: string
        format: uuid
      example: edb60e02-398d-4b62-8028-85710b2476a5
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
servers:
  - url: http://localhost
    description: Local Computer Environment
  - url: https://api-test.ebsi.eu
    description: EBSI Test Environment
  - url: https://api-pilot.ebsi.eu
    description: EBSI Pilot Environment
  - url: "https://api-conformance.ebsi.eu"
    description: EBSI Conformance Environment
