openapi: 3.0.3
info:
  title: Users Onboarding API
  description: |
    TODO
  version: 1.0.0
  termsOfService: /docs/terms
  contact:
    name: EBSI Support
    url: https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/ebsi
  license:
    name: EUPL-1.2
    url: https://joinup.ec.europa.eu/page/eupl-text-11-12
tags:
  - name: Users onboarding API
    description: List trusted DIDs
paths:
  /users-onboarding-api/v2/todo:
    get:
      tags:
        - Users onboarding API
      summary: todo
      description: todo
      operationId: todo
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  self:
                    type: string
                    description: URI to administrators
                  items:
                    type: array
                    description: List of administrators
                    items:
                      type: object
                      properties:
                        did:
                          type: string
                          description: DID of the administrator
                        href:
                          type: string
                          description: Link to the resource
                  total:
                    type: integer
                    description: Total number of items in a collection
                  pageSize:
                    type: integer
                    description: Number of items to be returned per page
                  links:
                    $ref: "#/components/schemas/Links"
              examples:
                Success:
                  value:
                    self: https://api.ebsi.xyz/users-onboarding/v2/administrators?page[after]=3&page[size]=10
                    items:
                      - did: did:ebsi:0x416e6e6162656c2e4c65652e452d412d506f652e
                        href: https://api.ebsi.xyz/users-onboarding/v2/administrators/did:ebsi:0x416e6e6162656c2e4c65652e452d412d506f652e
                      - did: did:ebsi:0x454253492d52554c45532d4d414c494e41524148
                        href: https://api.ebsi.xyz/users-onboarding/v2/administrators/did:ebsi:0x454253492d52554c45532d4d414c494e41524148
                    total: 124
                    pageSize: 10
                    links:
                      first: https://api.ebsi.xyz/users-onboarding/v2/administrators?page[after]=1&page[size]=10
                      prev: https://api.ebsi.xyz/users-onboarding/v2/administrators?page[after]=2&page[size]=10
                      next: https://api.ebsi.xyz/users-onboarding/v2/administrators?page[after]=4&page[size]=10
                      last: https://api.ebsi.xyz/users-onboarding/v2/administrators?page[after]=13&page[size]=10
        400:
          description: Bad Request Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Bad Paging Request:
                  value:
                    title: Bad Paging Request
                    status: 400
                    detail: PageSize should not be greater than 50
        500:
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
      parameters:
        - in: query
          name: page[after]
          schema:
            type: string
          description: Cursor that points to the end of the page of data that has been returned.
        - schema:
            type: integer
          in: query
          name: page[size]
          description: Defines the maximum number of objects that may be returned.
components:
  schemas:
    Problem:
      description: A Problem Details object (RFC 7807)
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type.
          default: about:blank
        title:
          type: string
          description: |
            A short summary of the problem type.
          example: Internal Server Error
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 400
          maximum: 600
          exclusiveMaximum: true
          example: 500
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the problem.
          example: Connection timeout
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
    Links:
      title: Links
      type: object
      properties:
        last:
          type: string
          description: URI of the last page
        prev:
          type: string
          description: URI of the previous page
        next:
          type: string
          description: URI of the next page
        first:
          type: string
          description: URI of the first page
      description: links model used for pagination
      x-examples:
        Links:
          first: https://api.ebsi.xyz/users-onboarding/v2/administrators?page[after]=1&page[size]=2
          prev: https://api.ebsi.xyz/users-onboarding/v2/administrators?page[after]=2&page[size]=2
          next: https://api.ebsi.xyz/users-onboarding/v2/administrators?page[after]=4&page[size]=2
          last: https://api.ebsi.xyz/users-onboarding/v2/administrators?page[after]=13&page[size]=2
    Attribute:
      title: Attribute
      type: object
      description: Attribute
      properties:
        hash:
          type: string
          description: sha256 hash of the payload
        body:
          description: Base64 encoded content
    AttributeDetails:
      title: attributeDetails
      type: object
      description: Attribute Details
      properties:
        did:
          type: string
          description: DID of the attribute owner
        attribute:
          $ref: "#/components/schemas/Attribute"
    Administrator:
      title: Administrator
      type: object
      description: Name of the administrator
      properties:
        did:
          type: string
          description: DID of the administrator
        attributes:
          type: array
          description: Array of attributes
          items:
            $ref: "#/components/schemas/Attribute"
    DIDMethod:
      title: DID Method
      type: object
      description: DID Method info
      properties:
        methodName:
          type: string
          description: DID Method name, e.g. "did:ebsi"
        ledgerName:
          type: string
          description: Name of ledger where DID Method is implemented, e.g. "ebsi-besu".
        methodSpec:
          type: array
          description: Array of bytes encoded serialized JSON method spec
          items:
            type: string
        methodSpecHash:
          type: array
          description: Array of bytes32 hashes (sha2-256) of the methodInfo element
          items:
            type: string
        notBefore:
          type: number
          description: Date and time after the DID method can be used.
        notAfter:
          type: number
          description: Date and time at or after the DID method must be considered invalid.
        status:
          type: number
          description: Status of the did method (1 = "active", 2 = "revoked", 3 = "suspended")
        did:
          type: string
          description: DID of the administrator
        attributes:
          type: array
          description: Array of attributes
          items:
            $ref: "#/components/schemas/Attribute"
    DIDDocument:
      title: DID Document
      description: DID Document as a JSON-LD document
      type: object
      additionalProperties: true
      properties:
        "@context":
          description: DID Document @context
          oneOf:
            - type: string
              format: uri
            - type: array
              items:
                type: string
                format: uri
    DIDDocumentMetadata:
      title: DID Document metadata
      description: DID Document metadata as a JSON document
      type: object
    DIDTimestamp:
      title: DID Timestamp
      description: DID Timestamp
      type: object
      additionalProperties: true
      properties:
        hash:
          type: string
          description: Multi-hash encoded hash
        timestampedBy:
          type: string
          description: Address of the transaction signer that timestamped the information.
        blockNumber:
          type: number
          description: Number of the block in which the hash has been timestamped.
        data:
          type: string
          description: Additional timestamp data.
    HashAlgorithm:
      title: Hash algorithm
      type: object
      properties:
        outputLengthBits:
          type: number
          description: Hash algorithm output length in bits. 0 if the output length if variable.
        ianaName:
          type: string
          description: Hash algorithm IANA name.
        oid:
          type: string
          description: Object identifier.
        status:
          type: string
          description: Status of the algorithm (active, revoked).
    Policy:
      title: Policy
      type: object
      description: Policy data model
      properties:
        policyId:
          type: string
          description: Unique policy ID
        policy:
          type: string
          description: Base64 encoded policy
        hash:
          type: string
          description: Hash (multihash) of the policy
    JsonRpcResponse:
      title: Json Rpc Response
      type: object
      properties:
        jsonrpc:
          description: Must be exactly '2.0'
          type: string
        id:
          description: Same identifier established by the client in the call
          type: integer
        result:
          description: Result of the call
          oneOf:
            - type: object
            - type: string
  examples:
    BadRequest:
      value:
        title: Bad request
        status: 400
        detail: Bad request
    NotFound:
      value:
        title: Not found
        status: 404
        detail: Not found
    InternalError:
      value:
        title: Internal error
        status: 500
        detail: Internal error
servers:
  - url: http://localhost
    description: Local Computer Environment
  - url: https://api.ebsi.xyz
    description: EBSI Testing Environment
