openapi: 3.0.3
info:
  title: Timestamp API
  description: |
    Timestamp API is a Core Service of the EBSI platform providing the
    capability of checking the authenticity of a digital document by
    verifying the presence and the timestamp of the document's hash
    in a specific smart contract.
  version: 2.0.0
  termsOfService: "/docs/terms"
  contact:
    name: "EBSI Support"
    url: "https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/ebsi"
  license:
    name: "EUPL-1.2"
    url: "https://joinup.ec.europa.eu/page/eupl-text-11-12"
paths:
  /timestamp/v2/jsonrpc:
    post:
      operationId: post-timestamp-v2-jsonrpc
      tags:
        - Timestamp API
      summary: Helper APIs
      description: |
        Helper APIs that assist the construction of blockchain transactions for Timestamp
        operations, and interaction with the ledger (Write operation on ledger)
      requestBody:
        required: true
        description: |
          The body follows the
          [JSON-RPC 2.0 specification](https://www.jsonrpc.org/specification).

          It requires the following fields:

          - **jsonrpc**: Must be exactly '2.0'
          - **method**: Method to be invoked. Possible values: insertHashAlgorithm,
            updateHashAlgorithm, timestampHashes.
          - **params**: Array of parameters
          - **id**: Identifier stablished by the client
        content:
          application/json:
            schema:
              required:
                - jsonrpc
                - id
                - method
                - params
              type: object
              properties:
                jsonrpc:
                  description: Must be exactly '2.0'
                  type: string
                method:
                  description: Method that needs to be invoked
                  type: string
                params:
                  description: Array of parameters
                  type: array
                  items:
                    type: object
                id:
                  description: Identifier stablished by the client
                  type: integer
                  example: 1
            examples:
              Build tx to insertHashAlgorithm:
                value:
                  jsonrpc: "2.0"
                  method: insertHashAlgorithm
                  params:
                    - from: "0x416e6e6162656c2e4c65652e452d412d506f652e"
                      outputLength: 256
                      ianaName: sha-256
                      oid: "2.16.840.1.101.3.4.2.1"
                      status: 1
                  id: 1
              Build tx to updateHashAlgorithm:
                value:
                  jsonrpc: "2.0"
                  method: updateHashAlgorithm
                  params:
                    - from: "0x416e6e6162656c2e4c65652e452d412d506f652e"
                      hashAlgorithmId: 3
                      outputLength: 256
                      ianaName: sha-256
                      oid: "2.16.840.1.101.3.4.2.1"
                      status: 2
                  id: 1
              Build tx to timestampHashes:
                value:
                  jsonrpc: "2.0"
                  method: timestampHashes
                  params:
                    - from: "0x416e6e6162656c2e4c65652e452d412d506f652e"
                      hashAlgorithmIds:
                        - 0
                      hashValues:
                        - "0x1234567890123456789012345678901234567890123456789012345678901234"
                      timestampData:
                        - "0xec45567890123456789012345678901fa456789012345678901234567890abfe"
                  id: 1
      responses:
        "200":
          description: Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JsonRpcResponse"
              examples:
                Build tx:
                  value:
                    jsonrpc: "2.0"
                    id: 1
                    result:
                      from: "0x416e6e6162656c2e4c65652e452d412d506f652e"
                      to: "0xFde86148db58f57787C06BeAf63a9c3f789357b3"
                      data: "0x0000..."
                      nonce: "0x00"
                      chainId: "0x1b3b"
                      gasLimit: "0x10000"
                      gasPrice: "0x00"
                      value: "0x00"
                Send Transaction:
                  value:
                    jsonrpc: "2.0"
                    id: 1
                    result: "0xe670ec64341771606e55d6b4ca35a1a6b75ee3d5145a99d05921026d1527331"
        "400":
          description: Bad request
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Bad Request:
                  $ref: "#/components/examples/BadRequest"
components:
  schemas:
    Problem:
      description: A Problem Details object (RFC 7807)
      type: object
      x-examples:
        Not Enough Credit:
          type: "https://example.com/probs/out-of-credit"
          title: You do not have enough credit.
          detail: "Your current balance is 30, but that costs 50."
          instance: /account/12345/msgs/abc
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type.
          default: "about:blank"
        title:
          type: string
          description: |
            A short summary of the problem type.
          example: Internal Server Error
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 400
          maximum: 600
          exclusiveMaximum: true
          example: 500
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the problem.
          example: Connection timeout
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
    JsonRpcResponse:
      title: Json Rpc Response
      type: object
      properties:
        jsonrpc:
          description: Must be exactly '2.0'
          type: string
        id:
          description: Same identifier established by the client in the call
          type: integer
        result:
          description: Result of the call
          oneOf:
            - type: object
            - type: string
  examples:
    BadRequest:
      value:
        title: Bad Request
        status: 400
        detail: Bad request
tags:
  - name: Timestamp API
    description: Validate timestamped records
servers:
  - url: "http://localhost"
    description: Local Computer Environment
  - url: "https://api.ebsi.xyz"
    description: EBSI Testing Environment
