version: "3.7"

services:
  users-onboarding-web-client:
    image: 305472350643.dkr.ecr.eu-central-1.amazonaws.com/ebsi/users-onboarding-web-client:prod_ebsiint-3061-terms-and-conditions_v1.0.0
    build:
      context: ../..
      args:
        PUBLIC_URL: ${PUBLIC_URL?Missing PUBLIC_URL variable}
        REACT_APP_EBSI_ENV: ${REACT_APP_EBSI_ENV?Missing REACT_APP_EBSI_ENV variable}
        REACT_APP_CAPTCHA_KEY: ${REACT_APP_CAPTCHA_KEY?Missing REACT_APP_CAPTCHA_KEY variable}
