version: "3.7"

services:
  trusted-ledgers-sc-registry-api:
    build: ../..
    image: 305472350643.dkr.ecr.eu-central-1.amazonaws.com/ebsi/trusted-ledgers-sc-registry-api:prod_ebsiint-2673-update-sc-info-by-name_v1.0.0
