version: "3.7"

services:
  did-registry-api:
    build: ../..
    image: 305472350643.dkr.ecr.eu-central-1.amazonaws.com/ebsi/did-registry-api:prod_ebsiint-2797-get-administrators-attributes-revisions_v2.0.0
